### ISSUE TITLE
Left associativity for operators?

### ISSUE THREAD

**Issue by jamesjrg** [lunet-io/scriban#100]
{{ 5 - 2 - 2 }}

currently shows 5, not 1, because the parser goes right to left when operators have the same precedence, not left to right as one might expect.

I found this line:
```
if (newPrecedence < precedence)
    break;

```
and wonder if maybe <= would fix it, probably not though! I can't test myself without booting up a Windows VM with full .NET framework and lacking enthusiasm for that right now.

Also maybe ScriptBinaryOperator.Substract: should be renamed without the typo, though guess it doesn't really matter.

**Comment by xoofx** [comment]
Ouch, good catch, thanks for that, this should be fixed by commit d1a8758 and available with scriban 2.0.0+

**Comment by xoofx** [comment]
Oops, introducing side regressions, will have to check a bit more deeply what is causing this....

**Comment by xoofx** [comment]
False alarm, it should be ok
