### ISSUE TITLE
How can I change the default token CodeEnter "{{"  and CodeExit "}}"

### ISSUE THREAD

**Issue by ShaffinR** [lunet-io/scriban#101]
Hi, 

I would like to change the default token start and end tags by my custom tags.

There are lot of JS templating engine using the same one. This can become very confusing.

Thanks

**Comment by xoofx** [comment]
It is not possible today. The lexer is hardcoding this. It is certainly feasible to adapt it to be configurable but this will be non trivial. As I don't have a special interest in this, PR welcome.

**Comment by xoofx** [comment]
Closing as wontfix
