### ISSUE TITLE
Bug with parsing `escape block` in the latest version

### ISSUE THREAD

**Issue by tatarincev** [lunet-io/scriban#102]
Used version the latest from `master` branch.

**Template** 
```XML
{% raw %} any content here {% endraw %}
{{ some_var }}
```
**Code**
``` C#
 var parsedTemplate = Template.ParseLiquid(content);
```
**Error message**
`
{<input>(1,24) : error : Error while parsing expression statement: Invalid token found `}`. Expecting <EOL>/end of line after: <expression>}
`

Thanks for great job. Keep it up!

**Comment by xoofx** [comment]
Indeed, good catch. It is fixed by commit dff2fb8 and should be available in `2.0.0-alpha-003+`
