### ISSUE TITLE
Event when token value can't be found

### ISSUE THREAD

**Issue by percramer** [lunet-io/scriban#111]
Hi,

great project! I was wondering if there is an event when the parse finds / get's a token from the lexer and it doesn't have a value for it. I would then like to run some of my own code which finds the results in a database.

Regards,

Per

**Comment by xoofx** [comment]
But what would be the behavior with this token? If you find it, you don't generate an error? What do you do with it according to the generated AST?

**Comment by percramer** [comment]
Well if i find a value for it then i pass it back in the arguments of te event so that scriban does get a value for the found token.

**Comment by xoofx** [comment]
> Well if i find a value for it then i pass it back in the arguments of te event so that scriban does get a value for the found token.

What do you mean scriban gets a value? You want to turn an unexpected symbol into what kind of AST?

**Comment by xoofx** [comment]
Instead of talking about something abstract here, do you have a concrete example why you are looking for this and how do you want to use it?

**Comment by percramer** [comment]
well what i would like to do is replace tokens in my strings with values. But not just a simple regex/replace, scriban offers some more features. If take a string :

"This is a {{ name }} template has got 2 {{ tokens }} "

The lexer will find 2 tokens in it and the parser will try to replace them with a value. If the parsers doesn't know what value to replace the {{ name }} token with, what happens then. Will it just leave {{ name }} in the string? Or can it fire an event so that i might give a value for {{ name }}?

**Comment by xoofx** [comment]
`name` or `tokens` are considered as variables and they will go through variable resolution. If they are not found, there is a last fallback on a `TemplateContext.TryGetVariable` that will ultimately try to resolve these names.

But you see, they are not invalid token, they are valid, so now you are talking about something different. That's variable resolution that you want, and you should be able to achieve this with `TemplateContext.TryGetVariable`

**Comment by alex-becker-startp** [comment]
I solved a similar use case by implementing my own `ScriptObject` class.
Within I've overwritten the `TryGetValue` method to provide the dynamic values.
Before parsing I assigned an instance of the `DynamicScriptObject` to the `TemplateContext`.
