### ISSUE TITLE
Evaluating string expression raise Exception error: InvalidOperationException

### ISSUE THREAD

**Issue by moh-hassan** [lunet-io/scriban#112]
Trying to evaluate string expression, as given below:
           
           var scriptObject1 = new ScriptObject();
            scriptObject1.Add("var1", "abc");
            var context = new TemplateContext();
            context.PushGlobal(scriptObject1);            
            var result = Template.Evaluate("var1.ToUpper()", context);              
            Console.WriteLine(result);

It raises an Exception:
>System.InvalidOperationException: This template has errors. Check the <Template.HasError> and <Template.Messages> before evaluating a template. Messages:
<input>(1,14) : error : Error while parsing nested expression: Expecting <expression> instead of `CloseParent` in: (<expression>)

Is there a limitation for evaluating expressions?

**Comment by xoofx** [comment]
> Is there a limitation for evaluating expressions?

No afaik, but you are calling a method on a .NET object with a .NET syntax. While this should expect a scriban syntax. You can't access methods on .NET objects, they are forbidden. You need to use a builtin function for example [`string.upcase`](https://github.com/lunet-io/scriban/blob/master/doc/builtins.md#stringupcase)
There are quite a few examples in the doc that should help.

**Comment by moh-hassan** [comment]
Thanks for reply.
I used string.upcase and it's working fine.
Really, i had to evaluate dotnet expression in c# syntax using scriban as an evaluating expression engine.
In this case, I had to parse the expression to convert it to scriban expression.
i.e var1.ToUpper()  ---> convert to -->string.upcase (var1)

**Comment by xoofx** [comment]
> Really, i had to evaluate dotnet expression in c# syntax using scriban as an evaluating expression engine

Yeah, that's not what Scriban is able to provide.
