### ISSUE TITLE
Render template with errors generously (e.g. skip blocks containing errors)

### ISSUE THREAD

**Issue by alex-becker-startp** [lunet-io/scriban#117]
Hello,

is there any option to render a script containing errors?
e.g. `This {{ 'template' }} {{ 'has }} {{ 'an error' }}` (closing quote missing in second block)

I would like to render this to the following result:
`This template {{ 'has }} an error`

Logic: Skip any block with errors and continue parsing at the next block.

Regards, Alexander.

**Comment by xoofx** [comment]
Well, in your case, it is difficult to recover. The opening `'has` is going to eat everything until the next `'` and then it will have a `an error'`  that will mean nothing... so no, in that case we can't do much I think
