### ISSUE TITLE
Controlling whitespace with control statement

### ISSUE THREAD

**Issue by ebekker** [lunet-io/scriban#118]
I have a template that goes something like this:

```
    {{- for item in itemList }}
    {{ if item.att1 }}[Att1]{{ end }}
    {{ if item.att2 }}[Att2]{{ end }}
    {{ if item.att3 }}[Att3]{{ end }}
    some fixed text

    {{- end }}
```

I'm trying to control the whitespace around the rendering of the [AttX] lines, so that when they are present, they preserve their line's whitespace, but when they're not, the line is not even there.  For example, if itemList had 3 items in it, with various combinations of attX values, they would render to something like this:

```
    [Att1]
    [Att2]
    some fixed text

    [Att3]
    some fixed text

    [Att1]
    [Att3]
    some fixed text

    some fixed text

```    

My intuition suggested that I put a greedy _whitespace eater_ on the right of each opening `if` statement, as in:

```
    {{- for item in itemList }}
    {{ if item.att1 -}}[Att1]{{ end }}
    {{ if item.att2 -}}[Att2]{{ end }}
    {{ if item.att3 -}}[Att3]{{ end }}
    some fixed text

    {{- end }}
```

This apparently has no effect.  The only thing that impacts the render is if I use whitespace eaters on the left of the `if` statement, or on the right of the `end` statement closing each `if`, but no combination of those achieves the desired effect.

How does the whitespace control work in the context of flow control statements?

**Comment by ebekker** [comment]
I think I figured it out, I guess the only way to do it is to split out the value across multiple lines, as in:

```
    {{~ for item in itemList ~}}
    {{~ if item.att1 ~}}
    [Att1]
    {{~ end ~}}
    {{~ if item.att2 ~}}
    [Att2]
    {{~ end ~}}
    {{~ if item.att3 ~}}
    [Att3]
    {{~ end ~}}
    some fixed text

    {{~ end ~}}
```

This appears to do what I'm aiming for.  Any other ideas on how to achieve the same effect using a more compact syntax?

**Comment by xoofx** [comment]
Maybe you can compress it a bit like this:
```
 {{~ for item in itemList
if item.att1 ~}}
    [Att1]
{{ end; if item.att2 ~}}
    [Att2]
{{ end; if item.att3 ~}}
    [Att3]
{{ end ~}}
    some fixed text

{{~ end ~}}
```
But yeah, otherwise, you can workaround it

**Comment by ebekker** [comment]
Got it, thanks for confirming I wasn't missing something.
