### ISSUE TITLE
Using customized functions

### ISSUE THREAD

**Issue by suntong** [lunet-io/scriban#12]
Following up on the closed issue #9 -- the solution provided there shows how to define a customized functions then use it. 

However, the normal case is that the template engine developers (those who define customized functions) and template engine users (those who use ready-defined customized functions) are different people. I.e., I need a mechanism to pre-define a bunch of customized functions, just like the string and math functions pre-defined in scriban, and allow normal users to use them just as the builtin functions. 

Because the code in #9 are tightly intertwined, I was having a hard time breaking it apart to achieve above without side affects. Is it possible to show how a customized-function registration mechanize can be put in place to register several functions for later consumption (for different templates & models)? Your help is really appreciated. 

Thanks a lot.

**Comment by xoofx** [comment]
You can import into a `ScriptObject` one function (as explained from issue #9) or multiple functions directly from a class (`scriptObject.Import(typeof(MyFunction))`). This is typically what is done for all builtins as ou said (See [Array](https://github.com/lunet-io/scriban/blob/master/src/Scriban/Helpers/ArrayFunctions.cs#L266) or [String functions](https://github.com/lunet-io/scriban/blob/master/src/Scriban/Helpers/StringFunctions.cs))

When you create a `TemplateContext`, you can pass a root ScriptObject, which acts as a namespace where everything defined on it is accessible from the script. But you can also push other level of objects with `context.PushObject(newScriptObject)`... `context.PopObject()`... so you can nest and control namespaces of your objects. 

Typically, you can create a 

```csharp
var globalFunction = new ScriptObject();
registerMyGlobalFunctions(globalFunction);
var localFunction = new ScriptObject();
registerMyLocalFunction(localFunction);

var context = new TemplateContext(globalFunction);
context.PushGlobal(localFunction);

var localObject = new ScriptObject();
context.PushGlobal(localObject);
page.Render(context);

context.PopGlobal(); // pop localObject
context.PopGlobal(); // pop localFunction
```
In the code above, the current script object would be `localObject`, so any variables set by the script would end-up into the `localObject` but you could call functions defined by `localFunction` and if not found there, it would try to resolve to `globalFunction`.

**Comment by suntong** [comment]
Works great. Thx. 

BTW, FTR, I can't get `new TemplateContext(globalFunction)` working, so I have to use the following workaround:

```
var context = new TemplateContext();
context.PushGlobal(globalFunction);

```
