### ISSUE TITLE
AND OR

### ISSUE THREAD

**Issue by shakykhan** [lunet-io/scriban#126]
Well its kind of basic question, but i am not able to find the AND OR functionality within if statement.

{{ if name == "abc" && class== "123" }} {{ if name == "abc" || class== "123" }} 
Above ones not throwing any error but its not performing as expected

{{ if name == "abc" AND class== "123" }} {{ if name == "abc" and class== "123" }} 
{{ if name == "abc" OR class== "123" }} {{ if name == "abc" or class== "123" }} 
Above one throwing error.

**Comment by xoofx** [comment]
The syntax should be `||` for OR and `&&` for AND as explained [here](https://github.com/lunet-io/scriban/blob/master/doc/language.md#85-conditional-expressions)

If it doesn't work, If you can post a very small repro that I can copy pasted, it might be a bug.
