### ISSUE TITLE
Change request to add a week function in date time functions

### ISSUE THREAD

**Issue by nazishqassim** [lunet-io/scriban#129]
Hi there,

I extremely love this project. This is not an issue but a change. I am working on a project and I need to extract the week number from the date field. Can it be implemented or can I extend the library to implement a custom function to calculate week?

Thanks a lot!

**Comment by xoofx** [comment]
Yep, no problem adding this I think, PR welcome

**Comment by nazishqassim** [comment]
Hi Alex,
I just realised that there is already a tostring function which returns the week of the date like date.to_string `%W`
This is working fine so no coding needed.
Thank you so much!
