### ISSUE TITLE
Unexpected value `True / Type: System.Boolean`. Cannot negate(-)/positive(+) a non-numeric value

### ISSUE THREAD

**Issue by devsienko** [lunet-io/scriban#136]
Hi!

I'm getting the error 'Unexpected value `True / Type: System.Boolean`. Cannot negate(-)/positive(+) a non-numeric value' when try to use such construction:

{{ if -5.32 > 0 }}
...
{{ end }},

but if I try {{ if (-5.32) > 0 }} it works fine

Thank you

**Comment by devsienko** [comment]
Is it issue or expected behavior?

**Comment by xoofx** [comment]
Likely a bug related to operator precedence

**Comment by xoofx** [comment]
Fixed in `2.0.0+`
