### ISSUE TITLE
Ability to set encoding mode

### ISSUE THREAD

**Issue by Weffe** [lunet-io/scriban#137]
Question: Is there an ability to set the default encoding mode?

For example, if I want to have to any HTML tags escaped I would have to pipe them into `html.escape` for every single time.

With other solutions, like `Fluid`, you have the ability to set the default encoder.
- https://github.com/sebastienros/fluid/#encoding
- https://github.com/Antaris/RazorEngine#general-configuration

Being able to set the default encoding mode, sets up the ability to set custom encoding modes as a developer.

**Comment by xoofx** [comment]
yep, PR welcome

**Comment by chaowlert** [comment]
You could also extend `TemplateContext` to format string.

```csharp
    class XmlTemplateContext : TemplateContext {
        public override string ToString(SourceSpan span, object value) {
            if (value is string s) {
                return WebUtility.HtmlEncode(s);
            }
            return base.ToString(span, value);
        }
    }
```

**Comment by jussik** [comment]
This may be a bit late, but overriding `ToString` causes multiple evaluations in pipelines and function calls (i.e. instead of escaping ">" to "\&gt;", it turns into "\&amp;gt;" or "\&amp;amp;gt;"). I fixed this by only encoding the results of statement nodes in `EvaluateImpl`:

	protected override object EvaluateImpl(ScriptNode scriptNode)
	{
		object value = base.EvaluateImpl(scriptNode);
		return scriptNode is ScriptExpressionStatement && value is string str
			? WebUtility.HtmlEncode(str) : value;
	}
