### ISSUE TITLE
DateTime Formating not working for Times in Liquid Templates

### ISSUE THREAD

**Issue by paul-developerconnections** [lunet-io/scriban#139]
I am using {{ date.parse travel_start_date | date.to_string '%d/%m/%Y %R' }} in a Liquid Template

Output 10/11/2019 00:00, the DateTime  Object has time as 16:05:00

**Comment by paul-developerconnections** [comment]
After some testing the format below works:

{{ date.to_string s.segment.start_date_time  "%H:%M"}}

**Comment by xoofx** [comment]
Closing if you found a workaround
