### ISSUE TITLE
Data from complicated source

### ISSUE THREAD

**Issue by suntong** [lunet-io/scriban#14]
Similar to #11, that the data is from deserialized source, but unlike #11, this time, the Json deserialization is not to a unstructured `var parsed`, but to a structured one. Yet, scriban seems unable to handle such case either. 

The data structure and data:

```csharp
    public class Specs
    {
        public string Storage { get; set; }
        public string Memory { get; set; }
        public string Screensize { get; set; }
    }

    public class Phone
    {
        public string Brand { get; set; }
        public string Type { get; set; }
        public Specs Specs { get; set; }
    }

    public static string json = @"[
          {
            'Brand': 'Nokia','Type' : 'Lumia 800',
            'Specs':{'Storage' : '16GB', 'Memory': '512MB','Screensize' : '3.7'}
          },
          {
            'Brand': 'Nokia', 'Type' : 'Lumia 710',
            'Specs':{'Storage' : '8GB','Memory': '512MB','Screensize' : '3.7'}
          },  
          { 'Brand': 'Nokia','Type' : 'Lumia 900',
            'Specs':{'Storage' : '8GB', 'Memory': '512MB','Screensize' : '4.3' }
          },
          { 'Brand': 'HTC ','Type' : 'Titan II',
            'Specs':{'Storage' : '16GB', 'Memory': '512MB','Screensize' : '4.7' }
          },
          { 'Brand': 'HTC ','Type' : 'Radar',
            'Specs':{'Storage' : '8GB', 'Memory': '512MB','Screensize' : '3.8' }
          }
        ]";
```

The test code: 

```csharp
        var deserialized =
            JsonConvert.DeserializeObject<List<Phone>>(json);
         Console.WriteLine("\n## Deserialize Phone List");
         Console.WriteLine(JsonConvert.SerializeObject(deserialized));
         Console.WriteLine(deserialized[0].Brand);
         Console.WriteLine(deserialized[1].Specs.Storage);
         //Console.ReadKey();

         var template = Template.Parse(@"{{ phones[0].Brand }}"); // phones[1].Specs.Storage
         var model = new { phones = deserialized };
         var scriptObject = new ScriptObject();
         scriptObject.Import(model);
         // Import the following delegate to scriptObject.myfunction (would be accessible as a global function)
         //scriptObject.Import("serialize", new Func<string>(() => "Hello Func"));

         var context = new TemplateContext();
         context.PushGlobal(scriptObject);
         template.Render(context);
         context.PopGlobal();
```

The output of `phones[0].Brand` is empty. If to use the commented out one, `phones[1].Specs.Storage`, an exception will be thrown. Note that both `deserialized[0].Brand)` and `deserialized[1].Specs.Storage` outputs just fine. 

Is there any possibility that scriban supports structured data like this? (I was trying to do the serialization myself within the template, passing `JsonConvert.SerializeObject` as customized function `serialize`, then using a loop to serialize each entry in `List<Phone>`.)

Thanks

**Comment by suntong** [comment]
I tried to change the `class` definition into `struct`, but result is the same:

```csharp
    public struct Specs
    {
        public string Storage;
        public string Memory;
        public string Screensize;
    }

    public struct Phone
    {
        public string Brand;
        public string Type;
        public Specs Specs;
    }
```

**Comment by suntong** [comment]
Confirmed that the issue has nothing to do with deserialization. I tried to construct a class array manually, and the result is exactly the same. 

The data structure:

```csharp
    /// ////////////////////////////////////////////////////////////////////////////
    // Class definition.
    public class Author
    {
        public string Name { get; set; }
    }

    public class Book 
    {
        public string Title { get; set; }
        public Author Author { get; set; }
    }

```

The test code:

```csharp
            Author a1 = new Author { Name = "John" };
            // http://www.functionx.com/csharp/arrays/Lesson03.htm
            Book[] b = new Book[2];
            b[0] = new Book();
            b[0].Title="Book1";
            b[0].Author = a1;
            b[1] = new Book();
            b[1].Title = "Book2";
            b[1].Author = a1;

            var globalFunction = new ScriptObject();
            // registerMyGlobalFunctions(globalFunction);
            StringFunctions.Register(globalFunction);

            var template = Template.Parse(@"This {{books[0].Title}} {{ ""is"" | mystr.upcase }} from scriban!");
            var model = new { books = b };
            var context = new TemplateContext();
            context.PushGlobal(globalFunction);

            var localFunction = new ScriptObject();
            localFunction.Import(model);
            context.PushGlobal(localFunction);

            template.Render(context);
            context.PopGlobal();
```

**Comment by xoofx** [comment]
By default, a `TemplateContext` has an active `IMemberRenamer` (through the property `TemplateContext.Renamer`), and the default renamer setup is [`StandardMemberRenamer`](https://github.com/lunet-io/scriban/blob/a96545d65a282d1f66f6111698b5296428188d38/src/Scriban/Runtime/StandardMemberRenamer.cs) which is basically transforming a camel/pascal case identifier to a lowercase+underscore identifier, meaning that:

- `Title` will be translated to `title`
- `SuperTitle` will be translated to `super_title` 

So in your example above, you should have something like: 

```csharp
var template = Template.Parse(@"This {{books[0].title}} {{ ""is"" | string.upcase }} from scriban!");
```
Note the slight difference: it is `books[0].title` instead of `books[0].Title`

All your questions are related to the [Runtime](https://github.com/lunet-io/scriban/blob/master/doc/runtime.md) document that was unfortunately not written when I finished the library. As I see the problems the lack of it can cause, I will try to find some time to start a first draft of this document, as it is obviously needed when using scriban beyong the simple helloworld sample! 😅

**Comment by xoofx** [comment]
I forgot also that you could also use `context.MemberRenamer = new DelegateMemberRenamer(name => name);` and it should just work without changing "Title" and "title". It may also solve the other issue #11 

Note that this rename doesn't affect the renamer used for all the builtins (which is by default the `StandardMemberRenamer`)

**Comment by suntong** [comment]
:+1:
