### ISSUE TITLE
What's the default HTML encoding behavior (Liquid and Scriban)?

### ISSUE THREAD

**Issue by jacobslusser** [lunet-io/scriban#140]
Love the project. 

I would like to know what the default HTML encoding behavior is for both Liquid and Scriban? i.e.
```
value = "<script>alert('attack!');</script>"
```
```
<h1>{{ value }}</h1>
```

Which of the following would it produce by *default*:
```
<h1><script>alert('attack!');</script></h1>
```
or
```
<h1>&lt;script&gt;alert(&#39;attack!&#39;);&lt;/script&gt;</h1>
```

**Comment by xoofx** [comment]
there is no encoding related to HTML, scriban is mostly agnostic about it's usage.

There is an `html.escape` function for example to escape a HTML string
