### ISSUE TITLE
TargetParameterCountException when trying to import a deserialized json object

### ISSUE THREAD

**Issue by mehdimadani** [lunet-io/scriban#144]
I am trying to import an object which is deserialized form a Json.
This code can reproduce the error:
`
static void Main(string[] args)
        {
            var json = "{'Users':[{'ID':'1','Name':'Test'},{'ID':'2','Name':'Test2'}]}";
            var obj = Newtonsoft.Json.JsonConvert.DeserializeObject(json);
            var scriptObject = new ScriptArray();
            scriptObject.Import(obj);
        }
`

**Comment by xoofx** [comment]
Import is not meant to be used on Dictionary objects (e.g the json object), you should just use the object directly.
