### ISSUE TITLE
Open solution in VS 2015 possible ?

### ISSUE THREAD

**Issue by bradws** [lunet-io/scriban#145]
Hey,
This look awesome, and good to know it supports .NET 4.5, but is there any possible chance you can produce a version so we can open it in Visual Studio 2015 ??? Pretty please...?

I've had a go at trying, but with no luck.

Thanks,
bradws.

**Comment by teo-tsirpanis** [comment]
Probably not; Scriban uses the new csproj file which is AFAIK not supported in VS 2015.

Is there a compelling reason that prevents you from upgrading to the more lightweight latest version?

**Comment by xoofx** [comment]
> This look awesome, and good to know it supports .NET 4.5, but is there any possible chance you can produce a version so we can open it in Visual Studio 2015 ??? Pretty please...?

We can't as we are using the new csproj which is not supported by VS2015. You can always fork it on your side and maintain an old csproj format if you are required to for your organization.

**Comment by bradws** [comment]
Yes!

The simple reason is that we don't have those higher versions of Visual
Studio.
We are unable to build the projects. Are there compiled binaries anywhere?

Cheers,

**Comment by xoofx** [comment]
> Are there compiled binaries anywhere?

Scriban binaries are shipped in a NuGet package

**Comment by bradws** [comment]
Thank-you, I will try these.
