### ISSUE TITLE
Importing object to scriptObject raise an exception: Parameter count mismatch, but anonymous object is working fine.

### ISSUE THREAD

**Issue by moh-hassan** [lunet-io/scriban#149]
var products = new List<Product> 
		{
		 new  Product {Id=100, name="aaa"},
		 new  Product {Id=101, name="bbb"},
		};
		var scriptObject1 = new ScriptObject();
               
               // this raise an exception: Parameter count mismatch
		scriptObject1.Import(products);

		//but using anonymous object new {products}     is working fine
		scriptObject1.Import(new {products});

            public class Product
		{
			public int Id {get;set;}
			public string name {get;set;}
		}

Should I use anonymous object new {products} to import products object?

**Comment by xoofx** [comment]
`import` here only works on reflection object, it copies properties from one object to another. But you can't import a list.
So when you do this : `scriptObject1.Import(new {products});` this is strictly equivalent to do this `scriptObject1["products"] = products` and I would use that instead.

**Comment by moh-hassan** [comment]
Thanks for reply,
 I'll take this into consideration when using List<>
