### ISSUE TITLE
What is the proper way of using Extension methods

### ISSUE THREAD

**Issue by moh-hassan** [lunet-io/scriban#150]
I have Extension methods that handle complex objects, like:

		public static class Extensions
		{
		//handle complex object of type Product
		 public static string DescribeProduct(this Product product)
		 {
		   return $"\t\tproduct id={product.Id}, Name= {product.name}";
		 }

 so, my template may be like this:

		{{ for product in products }}
			 {{product | DescribeProduct }}
		{{ end }}
	
	
To use the extension methods:

               // Setup a default renamer at the `TemplateContext` level
               var context = new Scriban.TemplateContext {MemberRenamer = member => member.Name};
		var scriptObject1 = new ScriptObject();
               //import extension methods
		scriptObject1.Import(typeof(Extensions));
		 

1) Is this the proper way to use the extension methods?

2) I get an exception  error: 
>error : Pipe expression destination `DescribeProduct` is not a valid function 

Should I use snake name for the method names although I set the context?

**Comment by xoofx** [comment]
You need to import with the renamer (e.g `scriptObject1.Import(typeof(Extensions), renamer = member => member.Name);`)
The MemberRenamer on TemplateContext is not globally shared but only when discovering objects when running the template.

**Comment by moh-hassan** [comment]
renamer solves the problem, just simple typo error :)

            scriptObject1.Import(typeof(Extensions2), renamer: member => member.Name);

It's fine if functions are auto discovered by the context.
Anyway, that extra line is not a big deal.
Thanks for help and support;
