### ISSUE TITLE
toDate with DateTimeOffset not displaying right time

### ISSUE THREAD

**Issue by farlock85** [lunet-io/scriban#152]
When I create this model:

```
var model = new
{
    date1 = DateTime.UtcNow,
    date2 = DateTimeOffset.UtcNow
};
```
I have to use the following template to print it:

```
{{ date1 | date.to_string '%b %d, %k:%M %p %Z' }}
<br/>
{{ date2.date_time | date.to_string '%b %d, %k:%M %p %Z' }}
```

I get the following results:
```
Mar 14, 19:42 PM +00:00 
Mar 14, 19:42 PM -06:00 
```
Both are showing the UTC date but when doing this in C#:
```
var a = model.date1.ToString("MMM d, H:mm tt zzz");
var b = model.date2.ToString("MMM d, H:mm tt zzz");
```
I get the results:
```
Mar 14, 19:45 PM +00:00
Mar 14, 19:45 PM +00:00
```
When I do in C#:
```
var a = model.date1.ToLocalTime().ToString("MMM d, H:mm tt zzz");
var b = model.date2.ToLocalTime().ToString("MMM d, H:mm tt zzz");
```
I get the result:
```
Mar 14, 13:47 PM -06:00
Mar 14, 13:47 PM -06:00
```
But there doesn't seem a way in scriban to convert the datetime object to local time.

I would assume that the behaviour is the same as in C# when passing UTC dates.

**Comment by nicholas-brooks** [comment]
@farlock85 - Your C# examples aren't making sense to me.  In the C# examples with "var a, var b", both statements would produce the exact same output as the lines are duplicates.

In any case, I'm not seeing the behaviour you demonstrate in the first section.  Using .net 4.7 and scriban 2.0.0 and this code:

```
public static void Main()
{
	var model = new
	{
		date1 = DateTime.UtcNow,
		date2 = DateTimeOffset.UtcNow
	};

	Console.WriteLine(model.date1.ToString("MMM d, H:mm tt zzz"));
	Console.WriteLine(model.date2.DateTime.ToString("MMM d, H:mm tt zzz"));

	var rendered = Render(@"{{ date1 | date.to_string '%b %d, %k:%M %p %Z' }}
<br/>
{{ date2.date_time | date.to_string '%b %d, %k:%M %p %Z' }}", model);

	Console.WriteLine(rendered);
}

public static string Render(string templateStr, object obj = null)
{
	var template = Template.Parse(templateStr);
	if (template.HasErrors)
		throw new Exception(string.Join("\n", template.Messages.Select(x => $"{x.Message} at {x.Span.ToStringSimple()}")));
	return template.Render(obj);
}
```

I get this output:

```
Mar 19, 1:04 AM +10:00
Mar 19, 1:04 AM +10:00
Mar 19,  1:04 AM +10:00
<br/>
Mar 19,  1:04 AM +10:00
```

**Comment by farlock85** [comment]
@nicholas-brooks is this on .NET Core? Because this is my output:
```
Mar 19, 1:21 AM +00:00
Mar 19, 1:21 AM -06:00
Mar 19,  1:21 AM +00:00
<br/>
Mar 19,  1:21 AM -06:00
```

**Comment by nicholas-brooks** [comment]
@farlock85  Ok, we're getting somewhere.  I get that as well.  So I'm assuming it is a .net core and .net full framework difference.  I'd suggest to log an issue at https://github.com/dotnet/core/issues

**Comment by farlock85** [comment]
I see yes, I did some more testing and it seems that there is either a change of behaviour or bug in .NET core, thanks!
