### ISSUE TITLE
Setting the MemberRenamer at the TemplateContext level - is documentation correct?

### ISSUE THREAD

**Issue by bradws** [lunet-io/scriban#154]
Hi,

This is a really good product.
Just wanting to know, is the documentation correct in the _Member Renamer_ section in the _Runtime_ documentation ?

I'm trying to set a Member Renamer at the _TemplateContext_ level. The documentation says do this:

`var context = new TemplateContext {MemberRenamer = member => member.Name};
`

.... but I don't think this is valid C# ?!?

Also, the TemplateContext class doesn't seem to have a constructor allowing a Member Renamer to be passed in. I ended up doing this (which worked perfectly):

```
var context = new TemplateContext();
context.MemberRenamer = new MemberRenamerDelegate( member => member.Name  );
```

Is there something I've done incorrectly? I'd be happy to contribute if you're in agreeance.
bradws.

**Comment by superjulius** [comment]
`var context = new TemplateContext {MemberRenamer = member => member.Name};`

This is definitely valid C# syntax (since C# 3.0) called [object initializer](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-initialize-objects-by-using-an-object-initializer).

What you wrote is also correct, just a bit more verbose.

@xoofx This is issue can be closed IMO

**Comment by holpit** [comment]
I have the same problem with a poco .Net c# object.
This configuration doesn't work: the case is not modified for imported object.

` var context = new TemplateContext
            {
                MemberRenamer = member => member.Name
            };
`
Instead, the same poco object with this configuration has the correct case:

`
  var scriptObject1 = new ScriptObject();
            scriptObject1.Import(poco, renamer: member => member.Name);
`
It seems that the configuration at TemplateContext doesn't affect Import.

**Comment by xoofx** [comment]
> I have the same problem with a poco .Net c# object.

Can you post a simple exe program that is showing exactly what you are trying to do and what is failing?

**Comment by holpit** [comment]
Hi @xoofx ,
Those are my tests for the problem mentioned above.
Thanks for you attention and let me known if you need additionals informations.

`public class MyObject
        {

            public string Hello = "hello from property!";
            public List<MyNestedObject> NestedObject = new List<MyNestedObject>() { new MyNestedObject() };
        }

        public class MyNestedObject
        {

            public int Value => 56;
        }

        public void IssueTest()
        {
            var scriptObject1 = new ScriptObject();
            scriptObject1.Import(new MyObject());

            var context = new TemplateContext();
            context.PushGlobal(scriptObject1);

            //Default behavior. OK
            var template = Template.Parse("This is Hello prop: {{hello}}. This is first nested value: {{nested_object[0].value}}");
            var result = template.Render(context);
            Console.WriteLine(result);
        }

        public void IssueTest1()
        {
            //MemberRenamerDelegate. OK if used in Import
            var scriptObject1 = new ScriptObject();
            scriptObject1.Import(new MyObject(), renamer: member => member.Name);

            var context = new TemplateContext();
            context.PushGlobal(scriptObject1);

            //Note that the NestedObject property Value, is imported in lower case. It seems that only root property are affected
            //by MemberRenamerDelegate (NestedObject[0].value instead of NestedObject[0].Value)
            var template = Template.Parse("This is Hello prop: {{Hello}}. This is first nested value: {{NestedObject[0].value}}");
            var result = template.Render(context);
            Console.WriteLine(result);
        }

        public void IssueTest2()
        {
            var scriptObject1 = new ScriptObject();
            scriptObject1.Import(new MyObject());

            //MemberRenamerDelegate. Not applied in this case
            var context = new TemplateContext
            {
                MemberRenamer = member => member.Name
            };
            context.PushGlobal(scriptObject1);


            //The render method cause  error: Object `NestedObject` is null.Cannot access indexer: NestedObject[0]
            var template = Template.Parse("This is Hello prop: {{Hello}}. This is first nested value: {{NestedObject[0].value}}");
            var result = template.Render(context);
            Console.WriteLine(result);
            
        }

        public void IssueTest3()
        {
            var scriptObject1 = new ScriptObject();
            scriptObject1.Import(new MyObject());

            //MemberRenamerDelegate. Not applied in this case
            var context = new TemplateContext
            {
                MemberRenamer = member => member.Name
            };
            context.PushGlobal(scriptObject1);

            //This is a mix and match. Root object with default renamer appliced, but nested are c# style. Note the .Value of nested object
            var template2 = Template.Parse("This is Hello prop: {{hello}}. This is first nested value: {{nested_object[0].Value}}");
            var result2 = template2.Render(context);
            Console.WriteLine(result2);

        }`

**Comment by holpit** [comment]
Hi @xoofx ,
Have you some news about this topic ?

**Comment by xoofx** [comment]
From your test above, you need to apply the MemberRenamer at both level:

- When you do an import to a ScriptObject (Because it's outside of TemplateContext, and the template context can't do that)
- When you access indirect objects

So you need to do:

```
scriptObject1.Import(new MyObject(), renamer: member => member.Name);
// AND
            var context = new TemplateContext
            {
                MemberRenamer = member => member.Name
            };
```

But not one or the others.

**Comment by xoofx** [comment]
This is what is explained in the documentation [here](https://github.com/lunet-io/scriban/blob/master/doc/runtime.md#member-renamer)

**Comment by holpit** [comment]
Good, 
I've written my test with your fix and now is all as expected.

Thank you.
