### ISSUE TITLE
Does Scriban support .NET Object Indexers ?

### ISSUE THREAD

**Issue by CADbloke** [lunet-io/scriban#159]
Firstly, thanks for this awesome library. I am investigating using it in an app that will retrieve data for CAD drawings of wiring diagrams for television stations, just in case you thought you'd heard every use-case.

My question: does the .NET object property retrieval support class indexers like `Thing["Index"]` where `Index` isn't an actual property but rather the argument for an indexer lookup? For a MSFT example on indexers - https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/using-indexers#example-2

cheers

**Comment by CADbloke** [comment]
I think I can answer my own question here: "not yet" and "looks tricky". Or it does and I missed it, 

Looking at https://github.com/lunet-io/scriban/blob/63ad634ffaf55cd4b8e72d1342f979520934c5be/src/Scriban/Runtime/Accessors/TypedObjectAccessor.cs at `TryGetValue` is only looks up fields and properties.  

I found https://stackoverflow.com/questions/14462820/check-if-indexing-operator-exists/14462921#14462921 for reference on indexers and how to find it.

I tried adding this code to `TryGetValue` ...

```c#
var indexer = _type.GetProperties().FirstOrDefault(p => p.GetIndexParameters().Length != 0
                                                      && !typeof(IList).IsAssignableFrom(_type));

if (indexer != null)
{
    object[] indexArgs = { member };

    try
    {
        value = indexer.GetValue(target, indexArgs);
    }
    catch (Exception )
    {
        return false;
    }
    return true;
}

return false;
```

but it broke .NET standard v1 & it also bypasses any filters etc. so it's not pull-request worthy. 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'Type' does not contain a definition for 'GetProperties' and no accessible extension method 'GetProperties' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	Scriban(netstandard1.1), Scriban(netstandard1.3)	D:\CodezOnD\Github\scriban\src\Scriban\Runtime\Accessors\TypedObjectAccessor.cs	63	Active
```

Your thoughts?

**Comment by xoofx** [comment]
The commit 14b0b171bd1937522c97eee6f45e2583a9ae4230 should fix this issue. it will be part of the next release

**Comment by CADbloke** [comment]
# Thank you!
Sorry about my delay in responding. This is much appreciated. I will put together some tests of the way I plan to implement it and let you know how I go. It will probably me a couple of months before I have my shit together but this definitely opens up a lot of possibilities.

Thanks again
Ewen
