### ISSUE TITLE
Function arguments as part of IScriptObject

### ISSUE THREAD

**Issue by pebezo** [lunet-io/scriban#160]
Hi,

I have a custom class that implements `IScriptObject` to make `{{ myobject.myproperty }}` possible while also throwing errors if an invalid `{{ myobject.foo }}` is used. This works great, but now I have the need to add functions to this object; something like `{{ myobject.myfunction 123 }}` where "123" would be a function argument. 

With `IScriptCustomFunction` I can access this value ("123") via  `ScriptArray arguments`. Is it possible to access arguments inside `IScriptObject` or would I have to have a function that takes `IScriptObject` as one of the arguments (like `{{ myfunction myproperty 123 }}`)?

Thanks!

**Comment by xoofx** [comment]
yeah, I think that you can only workaround it properly with something like `{{ myfunction myproperty 123 }}`

Scriban is not an OO scripting but more function based. The data can be accessed with sub-properties, but functions are only functions, not method with an implicit this attached to an object.

**Comment by pebezo** [comment]
Thanks for the confirmation and quick reply!
