### ISSUE TITLE
Prevent assignments in boolean expressions

### ISSUE THREAD

**Issue by pebezo** [lunet-io/scriban#164]
We've been using Scriban for a while in production (thanks!) and one (dangerous imo) pattern we've noticed is folks using a single "=" in "if" statements. Instead of `{{ if x == 2 }}` they write `{{ if x = 2 }}` which doesn't throw any exceptions and changes the values of `x` which causes confusion/bugs.

Is this something you'd be open to change? If yes, I could take a stab at a PR (any guidance as to where to start would be welcomed). Thanks.

**Comment by xoofx** [comment]
Yeah, it is not intended to be supported. I think that I added something around this (to prevent assignment) but only for expression statements... I guess assignment should only be allowed at the top level of an expression statement otherwise they should be disallowed...
PR welcome
