### ISSUE TITLE
Lazy evaluation of conditional expressions with boolean operators

### ISSUE THREAD

**Issue by koliyo** [lunet-io/scriban#166]
I have a potentially null object which I want to conditionally access subfield
```sbn
{{ if !a.foo || a.foo.bar }}
```

gives
```
Object `a.foo` is null. Cannot access member: a.foo.bar
```

I have verified that `{{ !a.foo }}` evaluates to `true`, so the `a.foo.bar` should never be evaluated.

Update: Even simpler test which fails with same error: `{{ false && a.foo.bar }}`

**Comment by xoofx** [comment]
Good catch, this is fixed by commit a48e94e and should be available shortly in 2.0.1

**Comment by koliyo** [comment]
Thanks for fix with `||`, but It is still problem with &&-evaluation.

```
{{ false && a.foo.bar }}
```
should not evaluate ` a.foo.bar`, but it does

**Comment by xoofx** [comment]
yeah, an oversight, could you send a PR to fix it?
