### ISSUE TITLE
Is it possible to pass values to attributes of the html element?

### ISSUE THREAD

**Issue by nazishqassim** [lunet-io/scriban#167]
Hi there,
I have a situation where I want to pass the source data to the attribute of the element. Is this possible with the engine?

For example, if the model has some base64 string, that I want to pass to the Image source, is is possible?
Model.SomeImage= "base64stringofimage"

Template:
&lt;img src=&quot;{{Model.SomeImage}}&quot; /&gt;

**Comment by pebezo** [comment]
From Scriban's point of view SomeImage is just a string, so this should work just fine. You just need to register you model with Scriban: https://github.com/lunet-io/scriban/blob/master/doc/runtime.md
