### ISSUE TITLE
Customized functions in their own "namespace"

### ISSUE THREAD

**Issue by suntong** [lunet-io/scriban#17]
Following on #16 ,

Alex, would you consider registering people's class with their own customized functions into their own "namespace"? -- In #16, the customized functions are available directly as `UpCase` & `DownCase`. Is it possible to have them available  in their own "namespace" as `MyLib.UpCase` & `MyLib.DownCase` (or `mylib.up_case` & `mylib.down_case` by default)? Thx.

**Comment by xoofx** [comment]
I explained this at the end of #16, simply create a new `ScriptObject` and sets a member "mylib" to the ScriptObject that got the imported functions.

```csharp
var mylib = new ScriptObject();
mylib.Import(...); // import functions

var globalObject = new ScriptObject();
globalObject.SetValue("mylib", mylib, true);  // true to make mylib variable as readonly
```

After on a TemplateContext, you can push as many outer ScriptObject as you want (as I explained, there is already a ScriptObject that imported all the builtins that is by default Pushed to the TemplateContext)

**Comment by suntong** [comment]
Thanks Alex!
