### ISSUE TITLE
How can I create "top-level" blocks and pass function parameters based on child-blocks?

### ISSUE THREAD

**Issue by deanebarker** [lunet-io/scriban#175]
I'd like to get to a point where I can use Scriban for componentized HTML generation. Here's an example of my ideal state, in the example of creating an captioned image block:

```
{{ image src: my-image.jpg }}
  {{ caption }}
     This is a really long-winded caption for this image, completed with paragraphs and stuff.
  {{ end }}
  {{ credit }}
    A long-winded image credit.
  {{ end }}
{{ end }}
```

The `image` block would call a function and pass the child blocks -- `caption` and `credit` as parameters. Or, even better, the `image` block would create an `Image` object with `Caption` and `Credit` properties, which could then be formatted into an HTML construct.

(This feels Markdig-ish to me. I've written an extension for that library which custom-parsed some text pattern and turned it into an object to be passed to a renderer. Effectively, I was able to create and populate and object from a text pattern. Same deal here, really. @xoofx, you're kinda familiar with Markdig... right? 😊 )

Given the current language constructs, how far off am I from being able to do this?  I realize this could probably be accomplished now with some combination of `wrap` or variable assignment and `include`, but like I said, this is my _ideal_ state.  Can I get there?

I think I need some way of creating a "top-level" function or block in Scriban. We discussed this a bit in #142, but the answer there was `wrap` sending information to a C# function. What if I didn't want the `wrap`, and I wanted to be able to call a function from the top-level and pass the parameters based on child block constructs?

If the answer is, "You will never be able to do this," that's fine. But given the architecture of the library, I'm left wondering if maybe there are enough hooks in it.

**Comment by xoofx** [comment]
> I think I need some way of creating a "top-level" function or block in Scriban. We discussed this a bit in #142, but the answer there was wrap sending information to a C# function. What if I didn't want the wrap, and I wanted to be able to call a function from the top-level and pass the parameters based on child block constructs?
> If the answer is, "You will never be able to do this," that's fine. But given the architecture of the library, I'm left wondering if maybe there are enough hooks in it.

You can certainly add a feature like this, but it is an annoying feature that I don't want to add, because the pluggability is specific, it requires to change the parser (you need to know upfront that a specific element is requiring a "end") and it makes it only available to configure it from C#
`wrap` is maybe slightly more verbose, but it is only a "wrap" keyword away, while not requiring dedicated changes (and maintenance) to the language parser.
