### ISSUE TITLE
The special variable "$$" cannot be filtered

### ISSUE THREAD

**Issue by deanebarker** [lunet-io/scriban#178]
This isn't an issue in the sense that I know why it's happening, but it might be something to note in the documentation.

The special variable `$$` appears to be different than other variables. I think its usage in the `wrap` statement is intended to pass code, not content, so it won't tolerate filters.

For example:

```
{{ func aside }}
<aside>{{ $$ | string.strip }}</aside>
{{ end }}
```

That will throw an error:

```
Error while parsing expression statement: Invalid token found `\|`. Expecting <EOL>/end of line after: <expression>
```

You can use filters with other function parameters (`$0`, `$1`, etc.), but not `$$`.

Again, think this is due to the special handling of `$$` as an intended code block, but it might be worth noting this in the doc.

**Comment by xoofx** [comment]
Yes, it can be a bit misleading as it is in fact as running the code referenced by $$ inlined, so it is not per-se a variable but a block of instructions.
But if you want to capture its content and do something with it, you can just use `capture` before using it in your wrapper function (something like that should work: `{{ capture myvariable; $$; end }}` and you can then use `myvariable`)
