### ISSUE TITLE
Default date/time format

### ISSUE THREAD

**Issue by suntong** [lunet-io/scriban#18]
How to specify a default date/time format for the scriban template engine?

In
https://github.com/lunet-io/scriban/blob/master/doc/language.md#dateto_string-format
it says, 

> Using date.now that would return the date `2013-09-12 22:49:27 +0530`

however, when I get my C# date/time variable from within the scriban template, the return that I got is `"2/24/2017 10:18:50 AM"`, whereas when I use JPATH select, the return that I got is `"2017-02-24T10:18:50.36"`, which is the format I want to keep. 

Oh, I'm still not 100% sure if it is the scriban template that is making the change because there is also Newtonsoft Json involved. But I've tried Newtonsoft Json separately, and it is working as expected. 

So, do you have any idea at which point the date format get changed? and how to fix it please?

Thanks

**Comment by suntong** [comment]
Confirmed that it is the scriban template that is making the format change, because my version of `{{ date.now }}` gives

`08 Mar 2017
`

as oppose to what documented in https://github.com/lunet-io/scriban/blob/master/doc/language.md#dateto_string-format

**Comment by xoofx** [comment]
The documentation is not correct at the beginning, but later it says that the default format is `%d %b %Y` which is correct to the behavior you are seeing.

There is currently no global format that you can set. You can always create a function that formats a parameter with the format you want and use it where you want to format the date.

**Comment by suntong** [comment]
Ok. That's the workaround I'm doing now (using a custom function), but hope you can find some time to enable global format setting. 

The fix itself is very easy which even I can help, but the real problem is how to define the API. Here are the two places to be fixed, for your convenient:

https://github.com/lunet-io/scriban/blob/8d8dbd1c426870d86ca97dae035f422a777910be/src/Scriban/Helpers/ScriptDate.cs#L216
https://github.com/lunet-io/scriban/blob/8d8dbd1c426870d86ca97dae035f422a777910be/src/Scriban/Helpers/ScriptDate.cs#L360

hope you can find some time to fix it. Thanks.

**Comment by xoofx** [comment]
I have added support for `date.format`  as a global format override (and `date.default_format` that contains always the original format. I have updated the doc accordingly.

Latest 0.3.0 version is bringing also regex functions (and some breaking changes to how builtin functions were registered)

**Comment by suntong** [comment]
Thanks Alex. 

I wasn't able to make mine working. After some digging, I found that the point where the date format get changed is not only output, but input as well. Here is demo:

```
var template = Template.Parse(@"This is {{ text }} on {{ date.format = '%Y-%m-%dT%H:%M:%S'; date.now; today }} from scriban!");
var model = new { text = "Hello Text", today = DateTime.Today };
var scriptObject = new ScriptObject();
```

and the output is 

`This is Hello Text on 2017-03-10T14:29:113/10/2017 12:00:00 AM from scriban!
`

I.e., the format of C# date/time variable seen from within the scriban template is still wrong. 

Sorry I wasn't very clear previous, as I didn't know exactly where the date format get changed. Thanks.

**Comment by hidegh** [comment]
@suntong, the date.format, this[default_format] etc. are all readonly. But this is how I altered the default format:
```
    // Set the default ISO format for all DateTime values
    var dateFunctions = context.BuiltinObject
        .First(x => x.Value.GetType() == typeof(DateTimeFunctions))
        .Value as DateTimeFunctions;

    if (dateFunctions != null)
    {
        var defaultDateTimeFormat = "%Y-%m-%dT%H:%M:%S";
        dateFunctions["default_format"] = defaultDateTimeFormat;
        dateFunctions.Format = defaultDateTimeFormat;
    }
```
