### ISSUE TITLE
Render enum as integer

### ISSUE THREAD

**Issue by danilosingh** [lunet-io/scriban#180]
How is best way to render enum as integer? It's possible?

>  public enum Enum
    {
          A = 1,
          B = 2,
          C = 3
    }
var template = Template.Parse(@"value: {{value}}")
template.Render(new { value = Enum.B })

Output: "value: 2"

**Comment by danilosingh** [comment]
``

**Comment by xoofx** [comment]
Unfortunately there is no builtin function for that. I believe you can workaround it with something like this: `{{value + 0}}` 
Not sure what kind of functions could be added/named to do that...

**Comment by danilosingh** [comment]
Ok! Thanks
