### ISSUE TITLE
Looping over Function Results

### ISSUE THREAD

**Issue by endeffects** [lunet-io/scriban#181]
I tried to migrate from Scriban 1.2.9 to 2.1.0, but i've noticed that some of my templates are getting not rendered anymore. The issue i have found here is, that it is no longer possible to loop over custom function results.

The following code worked with the old version, now the InvokedOn method i have injected to scribian gets called in both versions, but only for the old version the template loops over the result. Do i have to change something or is this a bug? Scriban itself throws no errors.

**Template**
```
    {{~ for entity in entities = InvokedOn aggregate.Id Entities ~}}
```

**Wire up**
```
    var context = new TemplateContext();

    var memberRenamer = new MemberRenamerDelegate( member => member.Name );
    context.MemberRenamer = memberRenamer;

    var templateExtensions = new ScriptObject();
    templateExtensions.Import(typeof(TemplateExtensions), ScriptMemberImportFlags.Method, null, memberRenamer);
            
    context.PushGlobal(templateExtensions);
```

**Extension** simplified
```
    public static class TemplateExtensions
    {
        public static IEnumerable<Entity> InvokedOn(Guid id, IEnumerable<Entity> entities)
        {
            return entities.Where(e => e.Id == id).ToList();
        }
    }
```

**Comment by xoofx** [comment]
> ``` {{~ for entity in entities = InvokedOn aggregate.Id Entities ~}}```

you should get an exception now. It is no longer possible to do an assignment outside of a top level...
you need to move the assignment to `entities` outside of the for

**Comment by endeffects** [comment]
oh to bad, it saved alot of code lines.

**Comment by xoofx** [comment]
Yeah, you can always do something like this:

`{{~ entities = InvokedOn aggregate.Id Entities; for entity in entities ~}}`

unless you don't need entities variable and you could collapse a bit more:

`{{~ for entity in (InvokedOn aggregate.Id Entities) ~}}`

**Comment by endeffects** [comment]
ah great, this solves my issue. thank you.
