### ISSUE TITLE
Null check in AND operator. If left is false both sides of AND are executed.

### ISSUE THREAD

**Issue by lygway** [lunet-io/scriban#191]
Null check in AND operator. If left is false both sides of AND are executed.

Where x is and empty List of strings. 
var x = new List<string>();
"{{ if x && x.size > 0 }}{{ end }}";

Results into:  ScriptRuntimeException, "<input>: error : Object `x` is null. Cannot access member: orderitems.size".

**Comment by sukhoi1** [comment]
![image](https://user-images.githubusercontent.com/7251500/63077713-ed81d880-bf41-11e9-86c7-7896ef71589f.png)

**Comment by sukhoi1** [comment]
if (!rightBoolValue) return false; // and expression evaluation should be stopped

**Comment by xoofx** [comment]
Thanks for the report. This is a pretty bad issue, I don't know what I was thinking when writing these lines, this is so basic... :(
I'm on vacation but I will have a look later next week

**Comment by xoofx** [comment]
Fixed by commit 5c748b7  will be available in 2.1.1+
