### ISSUE TITLE
[Question] Best approach to localization

### ISSUE THREAD

**Issue by Mortana89** [lunet-io/scriban#194]
Hello,

We're using Scriban as our templating engine to create various documenten, which we convert to PDF using puppeteer.
I was wondering, what would be the best approach to go for localization in these templates? More specifically, we work with enumeration classes extensively, and the actual symbols are exposed to the template to be able to make good conditional checks. However, sometimes we want to show a label of a symbol, in a userdefined language.

Do you have any best practice for this?

Thanks!

**Comment by xoofx** [comment]
I don't have, but just loading a dictionary from a file accessible in an object and then accessing loclization through it should be possible
