### ISSUE TITLE
Multi line comment breaks out before hitting ## }}

### ISSUE THREAD

**Issue by pebezo** [lunet-io/scriban#195]
Given this piece of code:

``` {{ ## now is: {{ date.now }} ## }} ```

I'd expect it to not render out anything (since it's commented out), but the actual output is:

``` ## }}```

It looks like the closing `}}` from `date.now` is closing out the comment block...

**Comment by xoofx** [comment]
Actually, that's not a bug but a "feature", it was to allow this:

```
{{ ## now is 
this is entirely commented
}}
```

Sorry, can't fix that in fact.

**Comment by mdamir** [comment]
This would be an important feature enhancement. Currently, the problem is that we cannot have code blocks commented out so as to reuse them in future.
For example, I should have been able to comment out like this:
```
{{## Commenting this out for now
{{for datacenter in Config.DcGroups[dcgroup].Datacenters}} 
					{
						"InstanceNamePrefix": "WordEditor.IPV4.{{datacenter.Name}}",
						"Parameters": {
							"endpoint": "{{datacenter.LivenessUriWordEdit}}&amp;SetApplicationEndpoint=ipv4.{{datacenter.Name}}-arr.officeapps.live.com&amp;corpnet=1"
						}
					},
##}}
```
So, @pebezo's suggestion seems perfectly fine and a good enhancement. Can we not address this easily?

**Comment by xoofx** [comment]
`##` is not meant to escape code. Use [escape blocks](https://github.com/scriban/scriban/blob/master/doc/language.md#13-escape-block) instead.

**Comment by xoofx** [comment]
> So, @pebezo's suggestion seems perfectly fine and a good enhancement. Can we not address this easily?

It would require a change in the parser to detect `{{` inside a comment. I don't have time nor an interest for this feature. If you really want that feature, you will have to bring a PR.
