### ISSUE TITLE
Globally disable member renaming?

### ISSUE THREAD

**Issue by waynebloss** [lunet-io/scriban#197]
Is there a way to globally disable member renaming without having to modify every call to `Render`?

If not, would you accept a pull request to add this?

I was quite frustrated by the default behavior because the initial example shown at the top of the README is very deceiving in my opinion. You can read [my comment on another issue](https://github.com/lunet-io/scriban/issues/38#issuecomment-533221029) to see exactly how I moved through your docs and why I missed the notice. At the very least, I think that notice should be moved higher and put into `RED` or something.

If you ever develop a new major version, I wonder if you would also consider disabling this as the default? What's the reason to make the default behave like `liquid` templates while also having a separate facility for parsing actual `liquid` templates?

Anyway, thanks for your code and your effort!.

**Comment by xoofx** [comment]
You can disable it as described [here](https://github.com/lunet-io/scriban/blob/master/doc/runtime.md#member-renamer). You should not have to patch everywhere this. Just make a small wrapper method and that should be it

```
var context = new TemplateContext {MemberRenamer = member => member.Name};
``` 

I will unlikely change this behavior. It has been the default from the beginning

**Comment by xoofx** [comment]
And there is a big warning on the readme, linking to exactly the link above, so I'm confused that you spend lots of time finding how to solve this.

**Comment by waynebloss** [comment]
I mentioned on my other comment:

> after looking at the very simple Hello, World use case I thought everything seemed pretty obvious. I skipped the next 2 examples because they were talking about liquid stuff that I didn't really care about. That's why I didn't even see the greyed out NOTICE at the bottom of the first section of the README...

> var context = new TemplateContext {MemberRenamer = member => member.Name};

Thanks. Don't you now have to pass this context to every call to `Render`? I was asking if there was a way to do it without having to wrap it. Did you not read my issue? (lol just kidding...)

I guess there isn't a way to do what I wanted to. No problem. Thanks again!

My only suggestion would be, to move that warning much higher in the README, not below the `Parse a Liquid template using the Liquid language:` section because by the time someone hits that section, if they don't care about Liquid and just want a simple text templating engine - they'll probably skip the rest of that section like I did.

**Comment by waynebloss** [comment]
Oh I also wanted to say that the big warning is very faint in color and does not stand out very much. Perhaps making it bold instead would also help.

**Comment by xoofx** [comment]
>  Don't you now have to pass this context to every call to Render? 

Do an extension method `MyRender` and you will won't feel the pain, it's really just an extension method away. That's way better than breaking a behavior.

**Comment by waynebloss** [comment]
Good point, thank you again! I had so many frustrations today ( with other stuff ) that I did not even have the creative energy to come up with that very nice and elegant solution.
