### ISSUE TITLE
Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0

### ISSUE THREAD

**Issue by ste-bel** [lunet-io/scriban#198]
I have this error when using Scriban in a web application :

Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

- The libraries used are the following:

Scriban.dll, version is 2.1.0.0
System.Threading.Tasks.Extensions.dll, version is 4.6.27818.1
System.Runtime.CompilerServices.Unsafe.dll, version is 4.6.26929.02

- This error does not occur on my local machine, only on the customer machine.
- My local .NET framework is 4.8.03752
- The customer's NET framework is 4.7.02558
- The code is compiled for 4.7.1

**Comment by xoofx** [comment]
Looks like an assembly redirect that you need to handle on your side. I don't think that there is anything we can do scriban side.

**Comment by ste-bel** [comment]
Merci Alexandre.
