### ISSUE TITLE
Caching - Pass a function into a function

### ISSUE THREAD

**Issue by endeffects** [lunet-io/scriban#199]
I'd like to build a caching mechanism to cache some results from custom functions i'm using.
But i'm allays getting an error that the original result can not be converted into Func<TResult>

Do you have any ideas how to get this done?

**Template**

`        {{~ result = (FromCache "cacheKey" (MyFunctionToCache someParameters)) ~}}`

**Custom Function**

```
        public static TResult FromCache<TResult>(string key, Func<TResult> func) where TResult : class
        {
            return functionCache.GetOrSet(key, func);
        }

    public class FunctionCache
    {
        private readonly MemoryCache memoryCache;

        public FunctionCache()
        {
            this.memoryCache = new MemoryCache(new MemoryCacheOptions());
        }

        public TResult GetOrSet<TResult>(string key, Func<TResult> factory) where TResult : class
        {
            return this.memoryCache.GetOrCreate(key, item => factory());
        }
    }
```

**Comment by xoofx** [comment]
I don't recall the details, but I think that generic functions are supported in scriban
