### ISSUE TITLE
Example on how to evaluate a boolean expression

### ISSUE THREAD

**Issue by pebezo** [lunet-io/scriban#20]
Hi,

I'm looking for a way to evaluate an expression with Scriban. 

Let's say I have a template like `{{ if customer.name == "Smith" }} Hi {{ end }}`. What I would like to do is evaluate the expression in the `if` statement without the rest of the template. Something like: `bool isSmith = context.EvaluateExpression("customer.name == \"Smith\"");`

Thanks

**Comment by xoofx** [comment]
While there is currently no method to parse directly an expression, you can do it by parsing the expression as part of a whole template, extract the expression from the ast, and run it through the context, something like this (note that the following code doesn't check for parsing errors, could avoid `{{ }}` by using directly the ScriptOnly mode of the underlying parser...etc.)

```c#
var stmt = Template.Parse("{{ customer.name == \"Smith\" }}").Page.Statements[0];
stmt.Evaluate(context);
var result = context.Result;
```

**Comment by pebezo** [comment]
Awesome! That worked!

(Linking here to the previous issue to be sure that you saw my comment: https://github.com/lunet-io/scriban/issues/19 -- not sure if me closing it hides it from your dashboard or not).

**Comment by xoofx** [comment]
Note that I have been updating scriban in several areas recently (with some breaking changes) and should also provide the runtime documentation as part of this.

As part of commit 8b374ff and 6808fe2,  I have added a static method `Template.Evaluate` that should do what you were originally looking for:

```c#
bool isSmith = Template.Evaluate("customer.name == \"Smith\"", context);
```

**Comment by pebezo** [comment]
Awesome; thanks!
