### ISSUE TITLE
And operations on conditionals don't work

### ISSUE THREAD

**Issue by lostllama** [lunet-io/scriban#206]
Environment: .NET Standard 2.0
Package: Scriban v2.1.0

If I write the following in a template:

    {{ true || false }}

Then when it's rendered it prints:

    true

But if I write

    {{ true && false }}

I get the following error:

    <input>(1,54) : error : Error while parsing expression statement: Invalid token found `&`. Expecting <EOL>/end of line after: <expression>

This is a simplification of an if statement that I was trying to work:

    {{ if testObject.child != null && testObject.child.childProperty }}
       it works! (is what I would say if it worked)
    {{ end }}

**Comment by xoofx** [comment]
Yeah, it should be fixed by 5c748b7ef34ad4336f13bba1286c087ccd5e0dc0
just that I haven't taken the time to push a new version

**Comment by lostllama** [comment]
> Yeah, it should be fixed by [5c748b7](https://github.com/lunet-io/scriban/commit/5c748b7ef34ad4336f13bba1286c087ccd5e0dc0)
> just that I haven't taken the time to push a new version

Oh sweet! :-) I've downgraded to 2.0.0 for the time being which seems to work. Thanks for your reply.
