### ISSUE TITLE
Formatting thousands in numbers

### ISSUE THREAD

**Issue by Oxyrus** [lunet-io/scriban#215]
Hello!

I've been reading throught the docs but so far I haven't been able to find a function that formats thousands in numbers by adding commas, like so:

`123456` becomes `123,456`

Does such function exist or should I do the formatting before passing it onto Scriban?

**Comment by Oxyrus** [comment]
After digging into the docs, I found you can chain pipes and use `object.format`.

**Comment by Jhaidee0123** [comment]
XDDDDDD
