### ISSUE TITLE
Possible to extract the properties from a file?

### ISSUE THREAD

**Issue by kevinhagenaars** [lunet-io/scriban#216]
Hi,
For a current project I need to extract certain values from a file into an object. I already generate files with the help of the scriban, but now I have to go the opposite way.

For example;

**File contents:**
`Hello World!`

**Template:**
`Hello {{name}}!`

**Result:**
`{
    "name":"World"
}`

Is it possible to extract the properties from a file into a (dynamic) object with a scriban template?
Thanks for your help/advice!

Kevin

**Comment by xoofx** [comment]
Sorry, that's not possible and out of the scope of Scriban.
