### ISSUE TITLE
Make the Constructor Protected

### ISSUE THREAD

**Issue by nfplee** [lunet-io/scriban#218]
Hi, I'd like to add a static ParseAndRenderAsync method (which combines the work of the Parse and RenderAsync methods) in the Template class. This will also allow me to set the TemplateContext (MemberRenameDelegate in the example below) so that I don't need to do it every time I render my templates.

I figured I could create my own Template class which inherits from The Scriban Template class. For example:

```
public class Template : Scriban.Template {
    public Template(Scriban.Parsing.ParserOptions? parserOptions, Scriban.Parsing.LexerOptions? lexerOptions, string sourceFilePath) : base(parserOptions, lexerOptions, sourceFilePath) { }

    public static async Task<string> ParseAndRenderAsync(string text, object model) {
        var template = Parse(text);

        var result = await template.RenderAsync(model, member => member.Name);

        return result;
    }
}
```

However this won't work since the constructor is private. Could you make the constructor protected?

**Comment by xoofx** [comment]
Why not using a extension method for this?

**Comment by nfplee** [comment]
Thanks that would work. I think for now I'm going to add a wrapper class which will allow me to customize it how I please. I'll close this.
