### ISSUE TITLE
Exceeding number of iteration limit `1000`

### ISSUE THREAD

**Issue by henriqueandradesilva** [lunet-io/scriban#219]
HI

Recently, an error occurred when it exceeds 1000 records and it is time to rederize

{"<input>(5,3) : error : Exceeding number of iteration limit `1000` for statement: for cliente in evento.clientes ... end"}

Whats this?

**Comment by xoofx** [comment]
As the primary usage of Scriban is for user scripts usually within shared containers/apps, it  comes with [default safe settings](https://github.com/lunet-io/scriban/blob/master/doc/runtime.md#safe-runtime) that you can modify.
