### ISSUE TITLE
Question: How do I get access to Span/location inside IScriptObject?

### ISSUE THREAD

**Issue by pebezo** [lunet-io/scriban#22]
Hi,

I'm using a custom IScriptObject like you recommended in #21. When there's an issue inside IScriptObject.TryGetValue, is there a way to gain access to the SourceSpan? 

My goal is to bubble up the location of the error back to the user. From IScriptCustomFunction is easy because we get access to the called context (ScriptNode.Span).

Thanks.

**Comment by xoofx** [comment]
Fixed by commit 757f98e
