### ISSUE TITLE
The function `include` was not found

### ISSUE THREAD

**Issue by pluveto** [lunet-io/scriban#221]
code:
```
{{ include '../_layouts/head.html' }}
```

>**Scriban.Syntax.ScriptRuntimeException: 'The function `include` was not found'**

How can I include a template?

**Comment by xoofx** [comment]
I can't make any proper diagnostics from this issue.
Please provide a small compile-able code that details how you are doing this and what is not working. Also have you read [Include and ITemplateLoader](https://github.com/lunet-io/scriban/blob/master/doc/runtime.md#include-and-itemplateloader)?

**Comment by pluveto** [comment]
code for testing:
```c#
using Scriban;
using Scriban.Parsing;
using Scriban.Runtime;
using System;
using System.IO;
using System.Threading.Tasks;

namespace Tester
{
    class Program
    {
        static void Main(string[] args)
        {            
            var inFilePath = @"D:\in.html";
            var template = Template.Parse(System.IO.File.ReadAllText(inFilePath));
            var obj = new ScriptObject();
            var context = new TemplateContext(obj);
            context.TemplateLoader = new MyIncludeFromDisk();
            Console.WriteLine(template.Render(context));
            Console.ReadKey();
        }
    }
    public class MyIncludeFromDisk : ITemplateLoader
    {
        public ValueTask<string> LoadAsync(TemplateContext context, SourceSpan callerSpan, string templatePath)
        {
            throw new NotImplementedException();
        }

        string GetPath(TemplateContext context, SourceSpan callerSpan, string templateName)
        {
            return Path.Combine(@"D:\", templateName);
        }

        string ITemplateLoader.GetPath(TemplateContext context, SourceSpan callerSpan, string templateName)
        {
            return Path.Combine(@"D:\", templateName);
        }

        string ITemplateLoader.Load(TemplateContext context, SourceSpan callerSpan, string templatePath)
        {
            return File.ReadAllText(templatePath);
        }
    }
}
```
file: `D:\in.html`
```html
 Head: {{ include 'head.html' }}
```
file: `D:\head.html`
```html
<b>This is head</b>
```

**Comment by xoofx** [comment]
You should not pass an object to TemplateContext:

```
            var obj = new ScriptObject();
            var context = new TemplateContext(obj);
``` 

Because this object is actually the one providing builtins:

https://github.com/lunet-io/scriban/blob/0beef58007219775a8203b0a5656b742ea9cac1b/src/Scriban/TemplateContext.cs#L95-L99

So just do `var context = new TemplateContext();` instead.

**Comment by pluveto** [comment]
Thanks for your reply. So I should pass model to `context.BuiltinObject` right?

**Comment by xoofx** [comment]
> Thanks for your reply. So I should pass model to context.BuiltinObject right?

Not really, `BuiltinObject` is really the root (builtin) object that is ultimately called after trying to resolve to your own model objects. If you want to pass your model, you can stack them with `context.PushGlobal`/`PopGlobal`. The builtin object is internally the first `PushGlobal` that you can't remove from the stack.

https://github.com/lunet-io/scriban/blob/0beef58007219775a8203b0a5656b742ea9cac1b/src/Scriban/TemplateContext.cs#L147-L148
