### ISSUE TITLE
Are Templates safe to be cached?

### ISSUE THREAD

**Issue by dev-day** [lunet-io/scriban#224]
Hi,

In the example, the two lines are as follows.

var template = Template.ParseLiquid("Hello {{name}}!");
var result = template.Render(new { Name = "World" }); // => "Hello World!" 

Is is possible to cache the template in memorycache, so that only the Render takes any time to process?

Thank you for your help in advance,
Regards,
Dev

**Comment by xoofx** [comment]
> Is is possible to cache the template in memorycache, so that only the Render takes any time to process?

yes, templates are meant to be cached.
