### ISSUE TITLE
Converting between System.DateTime and ScriptDate

### ISSUE THREAD

**Issue by pebezo** [lunet-io/scriban#23]
Hi,

When working with a System.DateTime value that came from a C# object and Scriban's built-in date functions I get:

```Object of type 'System.DateTime' cannot be converted to type 'Scriban.Runtime.ScriptDate'.```

Here's an example of a template that has this issue:

```{{ myobject.start_date | date.to_string `%d %b %Y` }}```

Would it be possible to have automatic conversions between System.DateTime and ScriptDate?

Thanks

**Comment by pebezo** [comment]
I could give this a try if you'd consider a PR.

**Comment by xoofx** [comment]
Actually, current design for `ScriptDate` is a bit problematic... It is most likely going to require a substantial change to remove the need for `ScriptDate` and allow to work directly with `DateTime`...

**Comment by xoofx** [comment]
As part of 494fbfd, I have removed `ScriptDate` and using only `DateTime`  we should avoid complicated conversions scenarios.
