### ISSUE TITLE
Pipe parameter passing order

### ISSUE THREAD

**Issue by RaveNoX** [lunet-io/scriban#232]
Hello,
thank you to make this great project!

During using this project, I was discovered some suprising behaviour, than looks like not very handfull.
This behaviour is documented, but making usage of pipes not so good as possible.
I tell about this behaviour:
> Notice that when using a function with pipe calls like {{description | string.strip }}``, the last argument passed to the string.strip` function is the result of the previous pipe. That's a reason why you will notice in all builtin functions in scriban that they usually take the most relevant parameter as a last parameter instead of the first parameter, to allow proper support for pipe calls.

Problem with this behavour, than I cannot declare fuction with optional argument and make it usable with pipes.

For example, I want to implement function `json` which serializes content to JSON, and want to use it with pipe in this way:
```
value | json
```

But this function on C# looks like:
```csharp
    internal static class TplHelpers
    {
        public static string Json(object value, bool pretty = false)
            => JsonConvert.SerializeObject(value, pretty ? Formatting.Indented : Formatting.None);
    }
```

And I also want to make possible usage like this:
```
value | json pretty: true
```
Currently it is not possible.

So it will be nice to pass pipe arguments to as the first parameter to a function, or make this behavour configurable on per function or template level.

Maybe it possible, but I not found how to make this.

**Comment by RaveNoX** [comment]
Sorry It looks like I parse my template as Liquid, in Scriban syntax all works fine.

But pipe arguments is passing as the first parameter (I tested this), so this sentense in documentation looks like not valid (or I not fully uderstand it):
> Notice that when using a function with pipe calls like {{description | string.strip }}``, the last argument passed to the string.strip` function is the result of the previous pipe. That's a reason why you will notice in all builtin functions in scriban that they usually take the most relevant parameter as a last parameter instead of the first parameter, to allow proper support for pipe calls.

**Comment by xoofx** [comment]
> Notice that when using a function with pipe calls like {{description | string.strip }}``, the last argument passed to the string.strip` function is the result of the previous pipe.

Oh right, this was originally like this, but it is no longer the case.

**Comment by xoofx** [comment]
I will update the doc

**Comment by RaveNoX** [comment]
Thank you
