### ISSUE TITLE
Whitespaces with include

### ISSUE THREAD

**Issue by cincuranet** [lunet-io/scriban#233]
Is there a way to keep the indentation from the origin for the included content? An example:

_some.include_
```
foo
bar
baz
```

_foo.template_
```
abc
  {{ include "some.include" }}
xyz
```

Expected output:
```
abc
  foo
  bar
  baz
xyz
```

**Comment by xoofx** [comment]
Actually no, but I can see the value. Let me try to see if I can include this into 3.0

**Comment by xoofx** [comment]
I have pushed a support for it to the 3.0 PR 6ed96e46839a244d31189eaea5d17ca756aa24ec

**Comment by cincuranet** [comment]
Awesome. Thanks.
