### ISSUE TITLE
Remove empty lines

### ISSUE THREAD

**Issue by Freshdouble** [lunet-io/scriban#235]
Is there a way to remove empty lines from the generated text?

I currently use scriban to generate code for multiple programming languages.
Because the template adds the language specific things, like loop structures, there is a pretty large amount of scriban code in the templates (i know that its not intended for this, but i want to remove language specific things from the C# code).
However scriban prints all lines that contain only scriban code as empty lines in the generated file so there are many white lines in the generated code.
Is there a way to tell scriban to delete all blank lines that result from the scriban code but not the blank lines that where in the template before?

**Comment by xoofx** [comment]
Have you tried to use [whitespace controls](https://github.com/lunet-io/scriban/blob/master/doc/language.md#14-whitespace-control)? (greedy or not)

**Comment by Freshdouble** [comment]
Sorry looks like i didn't read the manual careful enough. This actually solves my problem, thank you.
I'll close this issue since it's resolved.
