### ISSUE TITLE
Recursive local functions

### ISSUE THREAD

**Issue by orcun** [lunet-io/scriban#236]
The project that I faced this issue is getting much bigger than I anticipated. I was trying to organize custom functions into modules since I plan to open its source. I came up with something like the following:

```scriban
# main.sbn
{{
test = {}
include 'recursive.sbn` test
}}
{{ 13 | test.recursive # =14 }}
{{ 12 | test.recursive # =4 }}
```

```scriban
#recursive.sbn
{{-
$export = $1 ?? {}

func $recursive
  $n = $0
  if (($n % 2) != 0)
    ret $n + 1
  end
  ret ($n/2) | test.recursive
end

$export.recursive = @$recursive
-}}
```

This is far from ideal since I have to use `test.recursive` inside func `$recursive`. Of course, I want to be able to use this without knowing `$1` of include, in this particular case `test`. However I can't just use `$recursive` inside `func $recursive`. Is this intended? I also tried `$1.recursive` and `$export.recursive` with no luck. I also wonder what you think of this modular approach in general?

**Comment by xoofx** [comment]
Ok, that was in fact easy to bring. This should be part of upcoming 3.0 version.
