### ISSUE TITLE
Remove dependencies .NET 3.5 

### ISSUE THREAD

**Issue by lgcardonanet** [lunet-io/scriban#237]
Currently we use windows containers in Azure when deploying it throws us the error of the need .NET 3.5:

   Unable to find version '1.0.1' of package ****'jnm2.ReferenceAssemblies.net35'.****
      C:\Users\xxxxx\.nuget\packages\: Package 'j**nm2.ReferenceAssemblies.net35.1.0.1'** is not found on source 'C:\Users\xxxxx\.nuget\packages\'.
      https://api.nuget.org/v3/index.json: Problem starting the plugin 'C:\agent2\_work\_tasks\NuGetCommand_333b11bd-d341-40d9-afcf-b32d5ce6f23b\2.169.1\CredentialProviderV2\plugins\netfx\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe'. Plugin 'CredentialProvider.Microsoft' failed within 5.860 seconds with exit code -1.
    Unable to find version '1.0.0' of package 'Microsoft.NETFramework.ReferenceAssemblies'.
      C:\Users\malakaiadmin\.nuget\packages\: Package 'Microsoft.NETFramework.ReferenceAssemblies.1.0.0' is not found on source '

**Comment by xoofx** [comment]
This is fixed in 2.1.3
