### ISSUE TITLE
No way to negate boolean function return value in an if statement

### ISSUE THREAD

**Issue by rickms** [lunet-io/scriban#238]
I'm having an issue doing logic based on a custom c# boolean function and negation. 

I've first confirmed that my `has_annotation` function is working properly

```
        {{~ for variant in enum.variants ~}}
             {{~ has_annotation variant "Default" ~}}
             {{variant.value}} => {{enum.name}}::{{ variant.name }},
         {{~ end ~}}
```

outputs

```rust
true             0 => TagGroupType::Unsupported,
false             1 => TagGroupType::Standard,
false             2 => TagGroupType::Exclusive,
```

Turning that output into an if statement works as intended :

```
         {{~ for variant in enum.variants ~}}
             {{~ if has_annotation variant "Default" ~}}
             {{variant.value}} => {{enum.name}}::{{ variant.name }},
             {{~ end ~}}
         {{~ end ~}}
```

result in :

```rust
             0 => TagGroupType::Unsupported,
```

Now the behavior I want is the opposite of that, but nothing seems to make this possible:

using `!` infront of the function:

```
{{~ if ! has_annotation variant "Default" ~}}
```
results in a parse error:

` Invalid number of arguments '0' passed to 'has_annotation' while expecting '2' arguments`

using any combination of `==`, `!=` with `true`, `false`, `"true"`, `"false"` always results in `false`.

Is there a way to accomplish this without writing a negative custom function?

**Comment by rickms** [comment]
Additional note: 
```{{~ tmp = has_annotation variant "Default"; if ! tmp ~}}```
does manage to work.

**Comment by xoofx** [comment]
you need to use parenthesis `if !(has_annotation variant "Default");`

**Comment by rickms** [comment]
That does indeed work.  

> you need to use parenthesis `if !(has_annotation variant "Default");`

Thanks, that indeed did work for me.  Could have sworn I tried that at one point.  Thanks!
