### ISSUE TITLE
Camel-Case Render Error

### ISSUE THREAD

**Issue by yangxing5200** [lunet-io/scriban#239]
![image](https://user-images.githubusercontent.com/5023513/86119666-77f50b80-bb05-11ea-9ae8-f9ad47475654.png)

        class Test
        {
            public string NickName { get; set; }
        }
        [TestMethod]
        public void ScribanTest()
        {
          

            var obj = new { NickName = "Tingxing" };
            var dic = new Dictionary<string, string> { { "NickName", "Tingxing" } };
            var c = new Test
            {
                NickName = "Tingxing"
            };
            var t1 = Template.Parse("hello，{{NickName}}").Render(obj);// hello，
            var t2 = Template.Parse("hello，{{NickName}}").Render(dic);// hello，Tingxing
            var t3 = Template.Parse("hello，{{NickName}}").Render(c);// hello，

            System.Diagnostics.Debug.WriteLine(t3);

**Comment by xoofx** [comment]
You can read the explanation in the readme:


> **NOTICE**
>
> By default, Properties and methods of .NET objects are automatically exposed with lowercase and `_` names. It means that a property like `MyMethodIsNice` will be exposed as `my_method_is_nice`. This is the default convention, originally to match the behavior of liquid templates.
> If you want to change this behavior, you need to use a [`MemberRenamer`](/lunet-io/scriban/blob/master/doc/runtime.md#member-renamer) delegate
