### ISSUE TITLE
Replace Dictionary values In Scriban template Engine

### ISSUE THREAD

**Issue by AsadGilani** [lunet-io/scriban#241]
Dear Friends,
I am trying to use Scriban template engine for replacing the Dictionary Values. For Example
```
string bodyText = "Hi,
           The following service(s) has reported issues.
           {{emailContent}}
        Thanks " ;
Dictionary<string, string> keyValuePairs = new Dictionary<string, string>()
{
   {"emailContent",  "UserManagement has following unhealthy subservice(s)"}
};
 

 var template1 = Template.Parse(bodyText);
 var result1 = template1.Render(new { keyValuePairs[emailContent] = keyValuePairs });
 Console.WriteLine(result1.ToString());
```
But I am getting an error at the Render line. Basically want to replace that emailContent with Dictionary. values. I know I am doing some mistakes at render line. Can anyone point out my mistake or give any solution for that. 
Thanks

**Comment by AsadGilani** [comment]
No One replied yet.Please reply if someone have idea

**Comment by xoofx** [comment]
I'm on holiday, so not always connected these days.

Pass the dictionary directly instead of passing via an anonymous object:

```
 var template1 = Template.Parse(bodyText);
 var result1 = template1.Render(keyValuePairs);
 Console.WriteLine(result1.ToString());
```
