### ISSUE TITLE
Liquid string filter upcase not supported

### ISSUE THREAD

**Issue by 345paul** [lunet-io/scriban#242]
The Liquid string filter `upcase` doesn't appear in the list of Liquid built-in functions but seems to be a valid Liquid filter.  I'm not sure if this is a version of Liquid that isn't supported by the library and there is a workaround (use `string.upcase`) but would be nice if this was added to the Liquid built in functions.

**Comment by xoofx** [comment]
The list of functions are declared [here](https://github.com/lunet-io/scriban/blob/259821591960c6f9764f897c1dc56c2d0bddd118/src/Scriban/Functions/LiquidBuiltinsFunctions.cs#L39-L81), likely an oversight. PR welcome.

**Comment by 345paul** [comment]
I've submitted a PR - I hope I've followed convention.  I couldn't find a contributing guide.
