### ISSUE TITLE
How do you parse booleans?

### ISSUE THREAD

**Issue by BryanEuton** [lunet-io/scriban#243]
Simplified Scriban template to demonstrate question:

```
var template = Template.Parse("{{ $parsed = foo | bool.parse }}");
var result = template.Render(new { foo = "True"});
```
This throws the error: (1,25) : error : Object bool is null

**Comment by xoofx** [comment]
There are no functions for doing this directly today (as [`string.to_int`](https://github.com/lunet-io/scriban/blob/master/doc/builtins.md#stringto_int))

The closest you could do maybe something like `var template = Template.Parse("{{ if foo; $parsed = true; end; }}");`

**Comment by BryanEuton** [comment]
Thank you
