### ISSUE TITLE
xss handling

### ISSUE THREAD

**Issue by kijanawoodard** [lunet-io/scriban#247]
I may have missed it, but what's the scriban approach to preventing xss from ugc?
I was thinking maybe it encodes by default, but tested that to be false.
I then looked for a way to set some sort of default to include an encoding function?

Happy for a link for how others are handling this scenario.

**Comment by xoofx** [comment]
> I may have missed it, but what's the scriban approach to preventing xss from ugc?

I don't understand what do you expect. Could you give a concrete example with Scriban?

**Comment by xoofx** [comment]
(specially because talking about xss means more about browsers, but Scriban has nothing to do with browsers, so that's why I'm a bit lost here)

**Comment by kijanawoodard** [comment]
Yes. That makes sense. It's one reason that I chose scriban.

I happen to be using scriban for HTML pages served by a web server for a browser, thus the xss concern.

I wouldn't expect scriban to have a built in feature for this in the same way that, say, razor escapes by default.

What I was wondering if there is some way to provide a "pre-render delegate", e.g. Func<string, string>. I could then do any form of filtering or transformation that might be more easily done globally vs needing to adjust each field on each model given to Render.

**Comment by xoofx** [comment]
> What I was wondering if there is some way to provide a "pre-render delegate", e.g. Func<string, string>. I

You can try to override [TemplateContext.ToString](https://github.com/lunet-io/scriban/blob/259821591960c6f9764f897c1dc56c2d0bddd118/src/Scriban/TemplateContext.Helpers.cs#L73), but I don't think it is a good idea to perform xss at that level, you might start to filter things that you don't want to filter.

> I happen to be using scriban for HTML pages served by a web server for a browser, which happen to display UGC, thus the xss concern.

I would post-filter HTML pages fragment generated with Scriban by removing any javascript code. For example in https://babelmark.github.io/ it is possible to pass javascript, but the server will remove any javascript from the output. I didn't modify Markdig for this but only the HTML output.

**Comment by kijanawoodard** [comment]
Thank you.

I decided to take a two pronged approach.

1. My input sanitation will be beefed up substantially. If the valid values are only characters and numbers, that will eliminate angle brackets at the front door.

2. I'm filtering the html post scriban using anglesharp. I modified this post for my purpose: https://stackoverflow.com/a/63001220/214073.
