### ISSUE TITLE
Q: NullReferenceException 

### ISSUE THREAD

**Issue by AntonioSun** [lunet-io/scriban#25]
Please take a look at [this test code](https://github.com/AntonioSun/scdemo/blob/341d401c4bcbf343063057871af7510393379255/scDemo1/sc_demo1.cs#L84-L111)

I'm getting the following errors:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at Scriban.Runtime.ScriptObjectExtensions.Import(IScriptObject script, Object
 obj, ScriptMemberImportFlags flags, FilterMemberDelegate filter, IMemberRenamer
 renamer)
   at Scriban.Runtime.ScriptObjectExtensions.Import(IScriptObject script, Object
 obj)
   at Demo1.Program.Test2A() in D:\Git\a\scdemo\scDemo1\sc_demo1.cs:line 99
   at ProgTest.Main(String[] args) in D:\Git\a\scdemo\scDemo1\scd1_main.cs:line
13
```

However, I don't see any data issue as the function is very similar with [Test1A()](https://github.com/AntonioSun/scdemo/blob/341d401c4bcbf343063057871af7510393379255/scDemo1/sc_demo1.cs#L29). I [published the diff here](https://www.diffchecker.com/SYeoiJLt) for your convenient to check. 

I.e., I don't see any data issue as `Test1A()` is working fine. 

What's the real problem? How can I fix it? Thx!

**Comment by xoofx** [comment]
Can't make a diagnostic without digging into your code. Open another issue with a self contained reproducible bug (without having dependencies)

**Comment by AntonioSun** [comment]
OK... That's the best I could do though... 

By "dependencies" did you mean the Newtonsoft Json.NET library or something else? I put in above diff to show that problem has nothing to do with the Newtonsoft Json.NET, but, I'll see if I can strip it even further and still keep the problem. 

Thanks for looking into it.

**Comment by xoofx** [comment]
In the code above you posted, there are a bunch of stuffs like `Util.Scriban`...etc. that I don't know about. I need a simple code I can copy/paste into a single `Main(string[] args)` without having to understand all your sample context.

**Comment by AntonioSun** [comment]
In that case, the problem actually happens after I convert such simple code, to the current code structure. I guess I'm on my own now. OK...
