### ISSUE TITLE
Func parameters?

### ISSUE THREAD

**Issue by luikore** [lunet-io/scriban#256]
Can we have a more conventional way of declaring func parameters like:

```
func f foo bar baz
  ret foo + bar + baz
end
```

The above code should be translated into:

```
func f
  foo = $0
  bar = $1
  baz = $2
  ret foo + bar + baz
end
```

**Comment by xoofx** [comment]
This is provided by the upcoming 3.0 #230 where you can declare something like:

```
func f(foo, bar, baz)
  ret foo + bar + baz
end
```

There is a NuGet preview package available that you could probably try out...

**Comment by luikore** [comment]
@xoofx That's great!

One more question:

Why the definition form `f(foo, bar, baz)` is different from usage form `f foo bar baz`?

**Comment by xoofx** [comment]
> Why the definition form f(foo, bar, baz) is different from usage form f foo bar baz?

Because as part of scriban 3.0, there is now a mode for parsing a more scientific mode with also "inlined" function declaration:

```
f(boo, bar, baz) = foo + bar + baz
```

is equivalent to
```
func f(foo, bar, baz)
  ret foo + bar + baz
end
```

and because in this scientific mode you can call functions like `f(1,2,3)` it was also to make things consistent with default scriban lang mode.
