### ISSUE TITLE
Is "group" a reserved word

### ISSUE THREAD

**Issue by dev-day** [lunet-io/scriban#258]
Hi,

I use Scriban liqud parsing.
I have an object with a string called "group" and a value "ts1267".
When I debug the object before going into the templating process, I can see the value.

However, the {{ item.group }} returns nothing.
All other {{ item.xxx }} return their correct values.

I can only presume "group" is a reserved word?

Can you confirm?

If not, then can you let me know what could be causing this issue?

Dev

**Comment by xoofx** [comment]
Could you post a simple Program.cs repro? It could be an invalid usage on your side, but I can't guess from your description.

**Comment by dev-day** [comment]
Thank you for your feedback, it's helped a lot - appreciate it.
We have now resolved the issue.

**Comment by xoofx** [comment]
> We have now resolved the issue.

What was your problem? It could always help other folks here that might similar issue...

**Comment by drewlsvern** [comment]
@xoofx 

Years later I am experiencing what I believe is similar the previous issue @dev-day was experiencing. 

In my case it's {{ headerComment }} that is the issue.
```
var myTemplate = Template.Parse("Hello this is a {{ headerComment }}, this is a name: {{ name }}");

// headerComment doesn't get replaced, name does ---- why?
var result = myTemplate.Render(new {headerComment = "header comment.", Name = "John Doe." });
```

Sample repo below to replicate.

[Sample Repro](https://github.com/drewlsvern/scriban-reserved-word-repro/)

**Comment by xoofx** [comment]
It's in one of the very first thing in the readme:

> By default, Properties and methods of .NET objects are automatically exposed with lowercase and _ names. It means that a property like MyMethodIsNice will be exposed as my_method_is_nice. This is the default convention, originally to match the behavior of liquid templates. If you want to change this behavior, you need to use a [MemberRenamer](https://github.com/scriban/scriban/blob/master/doc/runtime.md#member-renamer) delegate

So you should change it to:

```c#
var myTemplate = Template.Parse("Hello this is a {{ header_comment }}, this is a name: {{ name }}");
```
