### ISSUE TITLE
date.toString does not support the culture parameter

### ISSUE THREAD

**Issue by workgroupengineering** [lunet-io/scriban#259]
Current behavior:

when use code like this:
```csharp
     var template = Scriban.Template.Parse(@"{{ data |  date.to_string ""%d_%a"" ""it-it""}}");       
     var resultCode = template.Render(new { Data = DateTime.Now });
```

throw exception: ScriptRuntimeException : Argument index must be < 2

affected version: relesae [3.0.0-alpha.9](https://github.com/lunet-io/scriban/releases/tag/3.0.0-alpha.9)

**Comment by xoofx** [comment]
This should be fixed in more recent 3.0.x
