### ISSUE TITLE
Help: I can't get func def working

### ISSUE THREAD

**Issue by AntonioSun** [lunet-io/scriban#26]
Sorry to bother you about a problem of my specific code -- 

Please take a look at [these two lines](https://github.com/AntonioSun/scdemo/blob/67816d2141fff4caeba95fc5637d1a41db59019b/scDemo1/sc_demo2.cs#L105-L106), which I wanted to include in the template above but failed. 

I.e., I _should have_ defined a custom function `select`, and `base.downcase` but somehow some where I didn't do it right so I can't access it. 

Sorry again to bother you with my specific problem. It's been a long day for me and my mind is not working. I'll look at it again tomorrow myself, and day after tomorrow, until I figured it out. Thx. 

**UPDATE**: I think I'm close -- got the first one working as `d[0] | select "".Specs.Storage""`. So somehow functions within `class TplUtil` (i.e., `base`) is not accessible. 

**UPDATE2**: Tried to use within the template, `base.getuuid` and `base.GetUuid`, but both give empty strings.

**Comment by xoofx** [comment]
You should have the following registered objects in your scriptobject:

- `select`
- `serialize`
- `base.get_uuid`
- `base.down_case`

**Comment by AntonioSun** [comment]
THANKS!!
