### ISSUE TITLE
ParseLiquid Functions

### ISSUE THREAD

**Issue by dev-day** [lunet-io/scriban#261]
Hi,

I'm using ParseLiquid.
Does this support custom functions either within the template or a .NET function?

Regards,
Dev

**Comment by xoofx** [comment]
> Does this support custom functions either within the template or a .NET function?

 .NET function only. Custom functions within the language are only supported with the Scriban syntax (`ScriptLang.Default` in 3.0+)

**Comment by dev-day** [comment]
Do you have any documentation on this?
I can see the scriban documention but cannot see how to use this in ParseLiquid as you cannot pass a context object?

**Comment by dev-day** [comment]
I currently use the line:

**mergedTemplate = scribanTemplate.Render(data, member => member.Name.ToLower());**

If I need to change this to use a context, how do I set the data and member to lower function?

**TemplateContext templateContext = new TemplateContext();
mergedTemplate = scribanTemplate.Render(templateContext);**
                        
Thank you for your help in advance.

**Comment by xoofx** [comment]
Have you looked at the [runtime](https://github.com/lunet-io/scriban/blob/master/doc/runtime.md) documentation, that are plenty of usages/examples?
