### ISSUE TITLE
IndentWithInclude causes error

### ISSUE THREAD

**Issue by badcel** [lunet-io/scriban#266]
The new `IndentWithInclude` property on `TemplateContext` causes an error if there is no indentation before an include.

Example project: https://github.com/badcel/ScribanBugIndentWithInclude

Error:
`Unhandled exception. <input>(2,3) : error : Specified argument was out of the range of valid values. (Parameter 'index')`

**Comment by xoofx** [comment]
This should be fixed in the next release `3.0.4`

**Comment by xoofx** [comment]
Oops, closed it to early, I still need to fix it, forgot about it in 3.0.4

**Comment by xoofx** [comment]
Ok, now this should be fixed in the next release 3.0.4 😅

**Comment by badcel** [comment]
Thank you very much :+1:.
