### ISSUE TITLE
IndentWithInclude: To much indentation?

### ISSUE THREAD

**Issue by badcel** [lunet-io/scriban#268]
I updated my repository https://github.com/badcel/ScribanBugIndentWithInclude with a new example.

With the IndentWithInclude feature activated the first line of 2 indented includes is indentet more than expected.

I wonder how to get the desired output?

**Comment by xoofx** [comment]
Good catch.
This should be fixed by commit 13f6091e128e8d2802089d7ab335984b0fd6165b and it's available in `3.0.5`
I have added more tests with more nested includes and I have found quite a few new issues. Hope that the most obvious one are solved now.

**Comment by badcel** [comment]
Thank you very much again 👍
