### ISSUE TITLE
Just wanted to say thank you

### ISSUE THREAD

**Issue by volkanceylan** [lunet-io/scriban#27]
Hello Alexandre,

I'm already using your MarkDig project in my blog at serenity.is. While searching for a template engine alternative to Razor / RazorGenerator for my code generation needs (sergen, e.g. Serenity CodeGenerator) came across this project, and with good experience from MarkDig wanted to give it a try. It took a few minutes to understand somewhat original syntax but in general it looks and works great and i'm going to certainly use it. I think there was a need for a lightweight template engine which support basic conditionals / expressions and Scriban fills that hole perfectly.

Thank you again, keep up good work!

**Comment by xoofx** [comment]
@volkanceylan thanks for the kind feedback, I appreciate 😊 

Indeed, I believe also that scriban can be handy for text templating, though I have still a few stuffs to polish (cleanup extensible points, cleanup api, documentation of the runtime, add a few more tests), a reason why I haven't made it much "public" so far, so it looks like still an underground project...

But your post tells me that I should really take the time to finish these final bits! 😉

**Comment by pebezo** [comment]
Yeah, let me second that as well. We've been using for a few months and it has worked beautifully; rock solid 👍
