### ISSUE TITLE
How to use TemplateContext/LoopLimit  with object Render

### ISSUE THREAD

**Issue by farukbenli** [lunet-io/scriban#271]
Hello,

I am trying to insert the Looplimit to change the 1000 default limit but my code is as below so couldn't integrate the context in it so far.

` dynamic obj = JsonConvert.DeserializeObject(data.RenderData.ToString());
            var template = Template.Parse(templateDef.Template);
            var result = template.Render(new { data = obj });`

Could you please guide me on how to change looplimit or use TemplateContext in this bit ?

Thanks, Regards Faruk

**Comment by xoofx** [comment]
There is a [runtime documentation](https://github.com/lunet-io/scriban/blob/master/doc/runtime.md) that gives plenty of examples of using TemplateContext directly, have you tried?

**Comment by farukbenli** [comment]
@xoofx Thank you for your reply, I did a scan of documentations but didn't see this one I had a workaround found yesterday but after taking a look at this it seems using dictionary is much better. 

Regards, Faruk

**Comment by ahmedanwar100** [comment]
```
var scriptObject1 = new ScriptObject();
scriptObject1.Import(new MyObject());

var context = new TemplateContext();
context.PushGlobal(scriptObject1);

var template = Template.Parse("This is Hello: `{{hello}}`");
var result = template.Render(context);

// Prints This is MyFunctions.Hello: `hello from method!`
Console.WriteLine(result);
```
Anyone who is facing a similar issue for loop-limit 1000, he/she can pass the data object to `scriptObject1.Import` and process it further like in the example above
