### ISSUE TITLE
Negative numbers in Liquid assign tags fail with "Invalid token found `-`"

### ISSUE THREAD

**Issue by Vanglant** [lunet-io/scriban#273]
Hi! I have experienced this in both 2.1.3 and 3.0.6 versions of the library. It happens when trying to parse the following statement for example: 
`{% assign test = -2 %}`

With the error: ``` This template has errors. Check the <Template.HasError> and <Template.Messages> before evaluating a template. Messages: <input>(1,18) : error : Error while parsing assign expression: Expecting <expression> instead of `Invalid` in: <target_expression> = <value_expression> <input>(1,11) : error : Error while parsing expression statement: Invalid token found `-`. Expecting <EOL>/end of line after: <expression>```

From what I can tell this should be valid syntax? It does work on http://dotliquidmarkup.org/try-online for example.

The main usecase is trying to use the splice `{{ "Liquid" | slice: -3, 2 }}` tag, this also fails currently.

Thanks!

**Comment by xoofx** [comment]
Oh, indeed, that was completely missing. It should be fixed by commit 3971b17 and available soon in 3.0.7
