### ISSUE TITLE
How to add custom function with the same prefix as a builtin function?

### ISSUE THREAD

**Issue by NeVeSpl** [lunet-io/scriban#274]
I would like to add a custom function with the same prefix as the prefix of one of the builtin functions, let's say `string.Foo()`.
How to achieve that in the most natural/idiomatic way for Scriban without losing access to built ones?

Also, bonus question is it possible to apply MemberRenamer for builtin functions without replacing `BuiltinFunctions` class with custom `ScriptObject`?

**Comment by xoofx** [comment]
> I would like to add a custom function with the same prefix as the prefix of one of the builtin functions, let's say string.Foo().
How to achieve that in the most natural/idiomatic way for Scriban without losing access to built ones?

Builtin functions are stored in a `ScriptObject` so you can always access them, modify them, add/or remove values/functions...etc. e.g `((ScriptObject)context.BuiltinObject["string"]).Import("Foo", (Action)MyFooImpl);`

> Also, bonus question is it possible to apply MemberRenamer for builtin functions without replacing BuiltinFunctions class with custom ScriptObject?

No. You would have to roll your own. Didn't want to introduce a different syntax for builtin functions as It would invalidate basically all the documentation or it would make code less portable.

**Comment by NeVeSpl** [comment]
thank you, works like a charm.
