### ISSUE TITLE
Allow to translate boolean value

### ISSUE THREAD

**Issue by totpero** [lunet-io/scriban#277]
Hi,

I want to use my custom value for boolean like Romanian translated values: true=> "da" and false => "nu" but [here ](https://github.com/lunet-io/scriban/blob/d9458f5655a9c6bb374e6a67620039d7f99b30c9/src/Scriban/TemplateContext.Helpers.cs#L129)is hard-coded "true" and "false" strings.

**Comment by xoofx** [comment]
You can override `ObjectToString`

**Comment by totpero** [comment]
I thing is very hard to override `ObjectToString` now, can you give me one example?
this is related to: https://github.com/lunet-io/scriban/issues/276
Thanks

**Comment by xoofx** [comment]
> I thing is very hard to override ObjectToString now, can you give me one example?

No sure to follow why do you think it is hard:

```csharp
        public class MyTemplateContext : TemplateContext {
            public override string ObjectToString(object value, bool nested) => value is bool b ? b ? "da" : "nu" : base.ObjectToString(value, nested);
        }
```

**Comment by totpero** [comment]
👍 Thanks, is very simple
