### ISSUE TITLE
Named parameters

### ISSUE THREAD

**Issue by pebezo** [lunet-io/scriban#28]
Hi,

Have you considered supporting named parameters with Scriban? Let's say I have a function "image" that requires three params: width, height, department. We'd call it like this:

`{{ image 300 400 210 }}`

As you can see, from a usage point of view, it's hard to know what those numbers mean. What if we could write it like this:

`{{ image width:300 height:400 department:210 }}`

The names (width, heigth, parameters) would be optional and only used for clarity. The order of the parameters could stay the same -- although being able to re-order them may be useful. That would open up a different can of worms though.

Thanks

**Comment by xoofx** [comment]
The parameter resolution would be quite costly and cumbersome to operate at this level, specially if you start to use pipes with them...etc. It would be difficult to keep this consistent with script custom function defined via `func`` which are only numbered (there is no parameter name/types definitions with `func`)

As a workaround, you could instead pass an object and decode this accordingly behind...

```
{{ image { width:300, height:400, department:210 } }}
```

**Comment by xoofx** [comment]
Actually, I have made a prototype of the idea yesterday, and while it complicates the arguments processing, it is still workable... I will check if I can bring this.

**Comment by xoofx** [comment]
So finally managed to add support for named arguments, without much performance impacts. I will add the documentation to the language reference (and runtime for the declaration)

So assuming you have declared  a function like this in C#

```C#
public static string Image(int width, int height)
{
...
}
```
You will be able to use the function like this:

```
{{ image width:300 height:400 }}
```

Note also that functions now support .NET default arguments.

This is part of the `0.14.0+` version
