### ISSUE TITLE
Using scriban with dictionary / dynamic object

### ISSUE THREAD

**Issue by clement911** [lunet-io/scriban#31]
Hi there,

I just discovered Scriban and I'm evaluating whether it would be a good fit for our project.
Basically we have some kind of reporting engine that query sql tables dynamically.

At compile time, we don't know the shape of the rows that are returned. The queried columns are dynamically selected by the user.

The object model that I would like to bind to the scriban templates looks something like this.

public class QueryResult
{
    public Dictionary<object, object>[] Rows { get;set; }
}

Each row is represented as a Dictionary<object, object>.
The keys can be either integer (the index of the column) or string (name of the column). It is a little bit like a [DataRow](https://msdn.microsoft.com/en-us/library/system.data.datarow).

Ideally, I'd like to be able to write Scriban templates that can access the cells in the row either by index or name.

However, I just did a few tests but I couldn't get Scriban to bind.

Here is my code:

```
var row = new Dictionary<object, object>();
            row["Pty"] = "My named pty";
            row[0] = "My indexed pty";

            var template = Template.Parse(@"
Named Property    {{row.pty}}
Indexed Property {{row[0]}}
");
            var result = template.Render(new
            {
                row = row
            });
```

Is it possible to achieve something like this?
It doesn't necessarily have to use a Dictionary. I thought something similar may be achieved by using an dynamic object (e.g. [expando](https://msdn.microsoft.com/en-us/library/system.dynamic.expandoobject), but again I'm not sure if that would work.

Any advice?

**Comment by xoofx** [comment]
Currently, script objects (either `Dictionary<TKey, TValue>` or `ScriptObject`) are accessed with a string as a key.

So the following should work:

```
var row = new Dictionary<object, object>();
            row["Pty"] = "My named pty";
            row["0"] = "My indexed pty";

            var template = Template.Parse(@"
Named Property    {{row.Pty}}
Indexed Property {{row[0]}}
");
            var result = template.Render(new
            {
                row = row
            });
```
Note that:
- Access to `row.Pty`, `Pty` is capital case. There is no renaming when you access a dictionary.
- We set `row["0"]` instead of `row[0]`

`ExpandoObject` typically is exposing members as strings.

**Comment by clement911** [comment]
That worked!
Merci Alex 👍
