### ISSUE TITLE
ScriptObject.Import

### ISSUE THREAD

**Issue by pavelkarinin** [lunet-io/scriban#35]
```
public class Base
{
    private string mParam1;
    private int mParam2;
    protected Base(string param1, int param2)
    {
        mParam1 = param1;
        mParam2 = param2;
    }

    public string Param1
    {
        private get
        {
            return mParam1;
        }
    }

    public int Param2
    {
        private get
        {
            return mParam2;
        }
    }
}

public class Child : Base
{
    private bool mParam3;
    public Child(): base ("value", 123)
    {
    }

    public bool Param3
    {
        private get
        {
            return mParam3;
        }
    }

    public void Test()
    {
        ScriptObject so = new ScriptObject;
        so.Import(this, ScriptMemberImportFlags.Property, renamer: member => member.Name);

        //so.Count => 0 ???

    }
}
```
https://github.com/lunet-io/scriban/blob/9c240ffabf1b5c15632c372e780e5ab1ea13ce82/src/Scriban/Helpers/ReflectionHelper.cs#L59

BindingFlags.DeclaredOnly | BindingFlags.Static

?

**Comment by xoofx** [comment]
Not sure what is your question exactly.

> //so.Count => 0 ???
> BindingFlags.DeclaredOnly | BindingFlags.Static ?

ScriptObject doesn't support to import private getter properties and your getters are all private in your example above (and it should not even compile, so not sure what you copy pasted)

**Comment by xoofx** [comment]
Ok, I believe that you were referring to the fact that it doesn't import parent properties. Indeed, this was a bug and should be fixed by commit cfe35cc 

Next please, take the time to formulate your issue, that's really not pleasant to deal with this kind of issue.

**Comment by pavelkarinin** [comment]
I'm sorry, but I do not speak English very well. The problem is that the properties inherited from the abstract class do not fall into the ScriptObject dictionary. Another nuance: when importing a .NET object, I noticed that the "static" flag is checked, i.e. property must be static?

**Comment by xoofx** [comment]
> I'm sorry, but I do not speak English very well. T

That's really ok! I really prefer some words than no phrases at all 😉 

> The problem is that the properties inherited from the abstract class do not fall into the ScriptObject dictionary. Another nuance: when importing a .NET object, I noticed that the "static" flag is checked, i.e. property must be static?

This should be fixed now. Instance and static properties are imported. You  can filter further down by passing a filter if you are looking for finer grained filter control.
