### ISSUE TITLE
Expected behaviour of date.to_string with nullable datetime

### ISSUE THREAD

**Issue by nicholas-brooks** [lunet-io/scriban#42]
Firstly thanks for making this library free and open source.

We've used dotliquid in the past for our templating needs.  One difference we've noticed is how a nullable DateTime is handled with date.to_string.

Firstly example object:

```
class Sample
{
    public DateTime? SampleDate { get; set; }
}
...

var sample = new Sample() { SampleDate = null };
```

Firstly, in scriban using ParseLiquid

```
var template = Template.ParseLiquid(templateStr);
Console.WriteLine(template.Render(sample));
```

The template:

```
The Date: {{ sample_date | date.to_string '%d %b %Y' }}
```

Results in:

```
The Date: 01 Jan 0001
```

However, in dotliquid, using this template:

```
The Date: {{ sample_date | date: "%d %b %Y" }}
```

would result in:

```
The Date:
```

Would you consider handling a null `DateTime?` like dotliquid (i.e. empty result)?  I'm happy to submit a PR if so.

**Comment by xoofx** [comment]
This should be fixed by commit 75583ef available in 1.1+
Thanks for the report!

**Comment by nicholas-brooks** [comment]
Excellent, thanks @xoofx !

Any idea on when 1.1+ will be released?

**Comment by nicholas-brooks** [comment]
Deleted my previous question re 1.1 release timeframe.  I see it has been released already!  Awesome!

Thanks again @xoofx .
