### ISSUE TITLE
Derived types

### ISSUE THREAD

**Issue by JoeBiellik** [lunet-io/scriban#43]
```cs
public class ClassA
{
    public string Value { get; set; }
}

public class ClassB : ClassA { }
```
```cs
var scriptObject = new ScriptObject
{
    {"a", new ClassA { Value = "ClassA" }},
    {"b", new ClassB { Value = "ClassB" }}
};

var context = new TemplateContext();
context.PushGlobal(scriptObject);

var result = Template.Parse("{{a.value}}-{{b.value}}").Render(context);
```
I'm expecting an output of ``ClassA-ClassB``, but only getting ``ClassA-``. If I change ClassB to not inherit from ClassA it works as expected.

I'm using v1.1.0 but this seems to be the same issue as #35 or am I missing something? Thanks.

**Comment by xoofx** [comment]
That's really a stupid bug, very similar to #35 but a different code path. Pushed a quick fix by commit 
bbcd86c

**Comment by JoeBiellik** [comment]
Thanks!
