### ISSUE TITLE
Is this project compatible with other open source project using MIT license?

### ISSUE THREAD

**Issue by Smilefounder** [lunet-io/scriban#48]
Hi, I found this project really awesome for .NET dev community. However, is this project compatible with other open source project using MIT license?

Thanks,

**Comment by xoofx** [comment]
Yes, it is a permissive license very similar to MIT with very few minor differences (see [license](https://github.com/lunet-io/scriban/blob/master/license.txt))

**Comment by Smilefounder** [comment]
Thanks @xoofx for the quick clarification.
