### ISSUE TITLE
Support for .NET Core ?

### ISSUE THREAD

**Issue by black-byte** [lunet-io/scriban#49]
Hello, are there any plans to provide support for .NET Core ?

**Comment by xoofx** [comment]
It is already as Scriban is compiled for `NetStandard1.1+ and NetStandard1.3+ running on CoreCLR`

**Comment by black-byte** [comment]
So why i can't install it ? 

VS cant find it on NuGet and on package manager console i got

PM> Install-Package Scriban -Version 1.2.0
Install-Package : Unable to find version '1.2.0' of package 'Scriban'.
At line:1 char:1
+ Install-Package Scriban -Version 1.2.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:00.0164961

**Comment by xoofx** [comment]
What is the type of target project?

**Comment by black-byte** [comment]
I tried on .NET Core 1.1 and 2.0 on a Console Project

**Comment by xoofx** [comment]
I just did it and it is working. Can you show the content of your csproj?

**Comment by black-byte** [comment]
Its total new console project

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

</Project>

```

**Comment by xoofx** [comment]
So you can't add a line like?

```xml

  <ItemGroup>
    <PackageReference Include="Scriban" Version="1.2.0" />
  </ItemGroup>
```

**Comment by black-byte** [comment]
When i added it and tried to build the project i got an error

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package Scriban. No packages exist with this id in source(s): CliFallbackFolder, Microsoft Visual Studio Offline Packages	TemplateParser	C:\TemplateParser.csproj	1	
```

When i tried 'restore nuget packages' on solution i got
```
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
Time Elapsed: 00:00:00.1773728
========== Finished ==========
```

**Comment by xoofx** [comment]
You have a problem with your nuget setup. Source repository nuget are screwed up or whatever is configure on your machine or in a local nuget.config....
Scriban is available on nuget https://www.nuget.org/packages/Scriban/1.2.0 and the dependencies show that it is compatible with netstandard1.x+

**Comment by black-byte** [comment]
Well, i still havent figured out how to solve this problem. But you are right on other PC it works fine.
