### ISSUE TITLE
StrictVariables does not work for complex objects (aka missing properties)

### ISSUE THREAD

**Issue by gunters63** [lunet-io/scriban#51]
Hi,

First thanks for the great library! We were evaluating DotLiquid and could not use it because we couldn't get it to work with serialized template parameters (it seems to require all parameter objects to derive from a special drop class).

We have one problem with Scriban now. We pass a complex object to a template and want to check if the object contains all the required template parameters.  We tried StrictVariables but it seems only to check if a variable exists, not if a property on a variable exists. That probably works as intended, but it means we can't check if the parameter object contains all needed values for the template to render.

Example (with LinqPad):

```` C#
	var context = new TemplateContext { StrictVariables = true };
	var aVar = new {a = new { b = "x"} };
	var scriptObject = new ScriptObject();
	scriptObject.Import(aVar);
	context.PushGlobal(scriptObject);
	var template = Template.ParseLiquid("Test: {{ a.b }}");
	template.Render(context).Dump();
````
will render correctly: Test: x

Changing the template to:

```` C#
	var template = Template.ParseLiquid("Test: {{ ax.b }}");
````

will throw a ScriptRuntimeException as expected.

Changing the template to:

```` C#
	var template = Template.ParseLiquid("Test: {{ a.bx }}");
````

will not complain und just render Test: 

Is there a way to do this?

Cheers, Gunter

**Comment by xoofx** [comment]
There are no options but you could try to setup a `TemplateContext.TryGetMember` and throw an exception if it goes there.

**Comment by gunters63** [comment]
Yeah, finally got back to this, it was really easy:

````
    var context = new TemplateContext
    {
        TryGetMember = (TemplateContext localContext, SourceSpan span, object target, string member, out object value) =>
            throw new ScriptRuntimeException(span, $"Parameter {member} is missing for template with id: {mailMessage.MailTemplateId}")
    };
    return template.Render(context);
````

**Comment by kishoresahas** [comment]
Below worked for me ! 
```
// Summary:
// Enables a member access on a null by returning null instead of an exception.
// Default is false
context.EnableRelaxedMemberAccess = true; 
```
