### ISSUE TITLE
Nested/Partial template support

### ISSUE THREAD

**Issue by HamedFathi** [lunet-io/scriban#52]
Does exist any `Nested/Partial template` feature in `Scriban`?

like `includes` in `dotLiquid` 
`https://github.com/dotliquid/dotliquid/wiki/DotLiquid-for-Designers#includes`
`https://github.com/dotliquid/dotliquid/issues/198`

**Comment by xoofx** [comment]
There is support for include in scriban, but you need to configure where the include are going and what they can return. There is a bit of documentation in the runtime [Include and ITemplateLoader](https://github.com/lunet-io/scriban/blob/master/doc/runtime.md#include-and-itemplateloader) and in the [language - include](https://github.com/lunet-io/scriban/blob/master/doc/language.md#99-include-name-arg1argn)

**Comment by sfmskywalker** [comment]
@xoofx I'm looking to do the exact same thing (have a "master" template that renders a "content" template, aka master/detail in webforms or "_layout"/RenderBody in Razor. However I'm having a hard time figuring this out from the documentation alone. I was able to implement my file-based `TempateLoader, but I'm missing something crucial. I'm essentially not sure what to put in the layout file.

Right now I have this:

_layout.liquid:
```
<html>
<body>
   (I want my content from my-content.liquid here)
</body>
</html>
```

my-content.liquid:
```
{{ include "_layout" }}
Hello World!
```

As you might expect, the output is simply a concatenation of _layout.liquid and my-content.liquid:

```
<html>
<body>
   (I want my content from my-content.liquid here)
</body>
</html>
Hello World!
```

This is the result I'm trying to achieve:

```
<html>
<body>
    Hello World!
</body>
</html>
```

Any pointers?

**Comment by sfmskywalker** [comment]
I was able to achieve my goal as follows:

**my-content.liquid**
```liquid
{{ capture content }}
Hello World!
{{ end }}
{{include "_layout"}}
```

_layout.liquid
```liquid
<html>
<body>
   {{ content }}
</body>
</html>
```

Which outputs:

```html
<html>
<body>
    Hello World!
</body>
</html>
```

Although this approach works for me, I'm still wondering if there's an alternative (recommended) way of doing this?

**Comment by bradlis7** [comment]
@xoofx Can we open this to formally request a better syntax for a layout file?

Perhaps simplify the structure of sfmskywalker's **my-content.liquid** to be:

```
{{layout "_layout"}}
Hello World!
```

I haven't seen a better way currently.

**Comment by srid** [comment]
There is one benefit to @sfmskywalker's syntax that isn't available in that of @bradlis7: support for more than one layout filler. For eg., I want to override not only _body_ but also the _title_. 

**my-content.liquid**

```liquid
{{ capture title }}My content{{ end }}
{{ capture content }}
Hello World!
{{ end }}
{{include "_layout"}}
```

**_layout.liquid**

```liquid
<html>
<head>
  <title>{{ title }} - My site</title>
</head>
<body>
   {{ content }}
</body>
</html>
```

Which outputs:

```html
<html>
<head>
  <title>My content - My site</title>
</head>
<body>
    Hello World!
</body>
</html>
```

---

In a way, this syntax is also more FP'ish than OO'ish. my-content.liquid behaves as if it is calling a function (the layout) with two arguments (title and body).
