### ISSUE TITLE
Can't access DataTable contents

### ISSUE THREAD

**Issue by slee-accesso** [lunet-io/scriban#53]
Hi!

Thanks for making your product - I'm very excited about it. However, I feel dumb - I cannot seem to access the results from a query or stored procedure. When I step through the code, I can see that the table has successfully been populated in the context object - but it won't let me see row data. I can access the data.table.rows.count property - but not data.table.rows[0][0]. Am I missing something? Here's the code I'm using in LinqPad:

```
void Main()
{
    var myTable = new customTable();
    myTable.table = MyStoredProcedure(3, 1, 11).Tables[0];
    myTable.Dump();
    
    var scriptObject = new ScriptObject();
    scriptObject["data"] = myTable;
    var context = new TemplateContext();
    context.PushGlobal(scriptObject);

    var EquipmentSizeTemplate = "Name Property: {{ data.name }} Data From Table: {{ data.table.rows[0][0] }}";
    var template = Scriban.Template.Parse(EquipmentSizeTemplate);
    var result = template.Render(context);
    result.Dump();
}

public class customTable
{
    public string name { get; set;}
    public DataTable table { get; set;}
    
    public customTable()
    {
        this.name = "TestName!";
    }
}

`````
Thanks for any help you can give.

  - Sean

**Comment by xoofx** [comment]
Scriban supports only `IList` for indexers but doesn't expose custom indexers. To workaround this, you can wrap the DataTable (e.g add rows to a ScriptArray object for example)
