### ISSUE TITLE
String to decimal conversion

### ISSUE THREAD

**Issue by uchirangv** [lunet-io/scriban#55]
Hi,
String to number conversion is not working for me. Here is the sample code -
``{{ a = '123' | math.plus 0`` Now, ``a | math.is_number }}`` is returning false. I even tried ``'123' | math.times 1``.

Basically i am trying to 1) convert '123456' to 123456 and 2) format it as 1,234,56. But i am stuck at 1).
I am using the latest nuget available in .Net framework 4.5 code.

**Comment by xoofx** [comment]
There is no automatic conversion from string to int (as I dislike this way as it could lead to some serious bug around) so the `+` operation for string is actually a concatenation.

By commit a7c8d50 I have added a few functions to perform this conversion `string.to_int` `string.to_long` `string.to_float`and `string.to_double`

**Comment by xoofx** [comment]
It should be part of 1.2.1+
