### ISSUE TITLE
Does not correctly parse <!doctype html>

### ISSUE THREAD

**Issue by vascofernandes** [lunet-io/scriban#56]
Hi,

Here is the template I am parsing:

```
+++
+++
<!doctype html>
<html>
<head>
{{~ include "head.scriban-html" ~}}
</head>
<body>
{{ $$ }}
</body>
</html>

```
and here is the C# code:
```csharp
var layoutPage = Template.Parse(scriptLayoutText, fullLayoutPath, null, new LexerOptions()
{
        Mode = ScriptMode.FrontMatterAndContent
});
```
And here is the parse result:

![image](https://user-images.githubusercontent.com/10337953/41421735-b6698cc0-6ff7-11e8-8aba-5c7d27b4a50b.png)

**Comment by xoofx** [comment]
What do you mean by parsing `<!doctype html>`? Scriban is working only at the text level, so it does not know anything about the text, I'm confused. What do you expect from the result?

**Comment by vascofernandes** [comment]
Hi, 

Thanks for the answer.
My mistake. 
Please close this.

Great project by the way 👍
