### ISSUE TITLE
CamelCase properties names in object

### ISSUE THREAD

**Issue by strejcradis** [lunet-io/scriban#57]
Hi guys,

im having problem with accessing properties of data object. If the properties names are camelCase, im not able to render the result correctly and exception is thrown. But when I convert properties names to snake_case with underline, everything works correctly.

Wrong object:
`{
    "email":"xxx.xxx@xxx.com",
    "order":
    {
        "idOrderExternal":"xxxxxxxxx",
        "totalPriceVat":
        {
            "numberInt":"1234"
        },
        "idOrderInternal":
        {
            "numberInt":"1234"
        },
        "date":"05.06.2018"
    }
 }`

Could anybody help me please how to be able to use objects with properties in camelCase? 

Thx.

**Comment by xoofx** [comment]
Just to make sure, have you tried [MemberRenamer](https://github.com/lunet-io/scriban/blob/master/doc/runtime.md#member-renamer) already as it is warned at the very beginning of the readme of this project?

**Comment by strejcradis** [comment]
Im sorry, will read carefully in future :/
