### ISSUE TITLE
Add a built-in function "obj.format"

### ISSUE THREAD

**Issue by Tyrrrz** [lunet-io/scriban#58]
That takes an `IFormattable` and converts it to string using given format. Essentially I'm suggesting moving `math.format` to `obj.format` since it accepts all values and is not limited to numbers. Would also be nice if you could specify culture info.

**Comment by xoofx** [comment]
I'm fine with this change. I would prefer to keep math.format at least to keep the compatibility (until a major bump). PR welcome (don't have enough spare time to work on this)

**Comment by Tyrrrz** [comment]
Cool I'll make a PR later this week
