### ISSUE TITLE
Add support to format float/decimals

### ISSUE THREAD

**Issue by jakejscott** [lunet-io/scriban#6]
Is there a way to call the objects `ToString()` method with a format specifier?

**Comment by xoofx** [comment]
Actually coming back to this issue, sorry for the delay  😞  ... wondering if you remember on what kind of objects you wanted to use a toString format specifier? (scriban doesn't strictly supports object methods, so it might be a function)

**Comment by superlogical** [comment]
It was actually on structs (double, float) so that you could format decimal places.

**Comment by xoofx** [comment]
Makes sense, will check that...

**Comment by xoofx** [comment]
Fixed by commit 662711c
