### ISSUE TITLE
date.now is cached and always returns the initial value

### ISSUE THREAD

**Issue by pebezo** [lunet-io/scriban#60]
Hi,

We're using version 1.2.0 and it looks like {{ date.now }} always returns the same value. You can test it by calling {{ date.now.second }}, waiting > 1s, and then calling it again (without shutting down the process).

Could it be that https://github.com/lunet-io/scriban/blob/master/src/Scriban/Functions/DateTimeFunctions.cs#L105 is not evaluated for each call?

Thanks

**Comment by xoofx** [comment]
Yes, that was an oversight, this property should be actually a method. All fields/properties on ScriptObject are transferred to it at initialization time. Will push a fix soon.

**Comment by xoofx** [comment]
Fixed in 1.2.2+

**Comment by pebezo** [comment]
Awesome... super fast response!! We downloaded the new version, pushed to prod, and it's working. Thanks!
