### ISSUE TITLE
Callback to skip sensitive information or determine which properties are discoverable

### ISSUE THREAD

**Issue by avataron** [lunet-io/scriban#64]
Is it possible to have a callback where we can determine which members are good to be parsed?

For example:
            var model = new User() { Name = "World", Password = "*****" };
            var template = Template.Parse("Hello {{name}}! I hacked your password/hash: {{password}}");
            var result = template.Render(model);

See? One can sniff information that are not for his nose.
I think we can have a delegate so we can protect this.

Actually, the Render method could optionally have a delegate to this signature:
            bool IsPropertyRetrievable(PropertyInfo property) //or a better method name

Then we can use this way:
            var result = template.Render(model, property =>  property.Name != "Password");

Note thats only an example, that's not limited to property name. We could have our own IsPasswordAttribute and whatever we need to check if the information is sensitive with this delegate.

What do you think?

**Comment by avataron** [comment]
Found where it can be placed. It's in Template.cs file:


        /// <summary>
        /// Renders this template using the specified object model.
        /// </summary>
        /// <param name="model">The object model.</param>
        /// <param name="memberRenamer">The member renamer used to import this .NET object and transitive objects. See member renamer documentation for more details.</param>
        /// <param name="memberFilter">NEW PARAMETER DESCRIPTION</param>
        /// <returns>A rendering result as a string </returns>
        public string Render(object model = null, MemberRenamerDelegate memberRenamer = null, MemberFilterDelegate memberFilter = null)

            var scriptObject = new ScriptObject();
            if (model != null)
            {
                scriptObject.Import(model, renamer: memberRenamer, filter: memberFilter); //<-- here. memberFilter
            }

**Comment by avataron** [comment]
Nvm. Resolved this way:

            bool filter(MemberInfo m) => m.Name != "Password";

            var scriptObject = new ScriptObject();
            scriptObject.Import(model, filter);

            var context = new TemplateContext();
            context.MemberFilter = filter;  //required again, to handle inner objects

            context.PushGlobal(scriptObject);
            var result = template.Render(context);

**Comment by xoofx** [comment]
Yes, the `MemberFilterDelegate` is for this purpose but it was not directly accessible on the Template frontend. This should be fixed by 0782820 and is being pushed for the next version `1.2.3`
