### ISSUE TITLE
Calling methods on .NET instances

### ISSUE THREAD

**Issue by InfinitiesLoop** [lunet-io/scriban#67]
I know methods aren't accessible for security reasons, that's good. But I have a scenario where it'd be handy to enable them. At first I thought a MemberFilter would let me opt into that, but looking at the code it looks like a MemberFilter can only be _more_ restrictive than the built-in filtering, not _instead of_ the built-in filtering. Is there any reason not to allow more flexibility?

https://github.com/lunet-io/scriban/blob/a6780cb8878cdfa92a0bdfce61caa7aa2809d3b8/src/Scriban/Runtime/Accessors/TypedObjectAccessor.cs#L83

**Comment by xoofx** [comment]
Yeah, sorry, this is more restrictive because instance methods are really not supported behind this filtering.
