### ISSUE TITLE
math.format with culture info

### ISSUE THREAD

**Issue by JakobMoser** [lunet-io/scriban#68]
Is there a way to format a number with `math.format`  with a specific culture info?

Something like `{{myPrice | math.format "N" "de-DE"}}`

**Comment by gunters63** [comment]
Hi Jakob,

You can only set the culture once per render globally, like this:

````
	var context = new TemplateContext();
	context.PushCulture(CultureInfo.CreateSpecificCulture("pt-PT"));
        template.Render(context)
````

And I had to use object.format, not math.format. math.format didn't work with template parameters for me.

**Comment by xoofx** [comment]
I was on holidays last week. The support for culture is added by commit d23b2ad and should be part of scriban `1.2.4+`
