### ISSUE TITLE
How do I register a custom function?

### ISSUE THREAD

**Issue by superlogical** [lunet-io/scriban#7]

**Comment by superlogical** [comment]
I worked it out  :+1: 

````csharp
var script = new ScriptObject();
script.Import(model);
script.SetValue("custom", ScriptObject.From(typeof(CustomFunctions)), true);
                
TemplateContext context = new TemplateContext();
context.PushGlobal(script);

Template template = Template.Parse(html);
template.Render(context);
context.PopGlobal();

string rendered = context.Output.ToString();
````

**Comment by xoofx** [comment]
your solution imports all public functions from `CustomFunctions` into an object and associate it to the `custom` variable (so it is more import multiple functions!)

You may also use `ScriptObject.Import(name, delegate)`  (or use a `new Func<...>(function)` as a delegate) in case you want to import a specific function or a this/closure function.

**Comment by superlogical** [comment]
Which looks like this if anyone struggles with Func syntax like I do :)

````csharp
Func<double, string> currency = value => value.ToString("C");
script.Import("fmt", currency);

// Or like this.
script.Import("fmt", (Func<double, string>)(value => value.ToString("C")));
````
