### ISSUE TITLE
Support of mixing decimal ValueType with int or double or ...

### ISSUE THREAD

**Issue by Robiwahn23** [lunet-io/scriban#72]
If you use/mix decimal properties with properties of other valuetypes (like int) within expressions, one of the value cannot be converted.
Example:
`{{ if obj.decimal_value > 0 }} `
-> throws exception:
Scriban.Syntax.ScriptRuntimeException:  Unable to convert type `System.Int32` to `System.Decimal`

**Comment by xoofx** [comment]
Good catch, this should be fixed by commit 34bd596 and available in `1.2.6+`
