### ISSUE TITLE
Numbers in templates should be parsed using the InvariantCulture

### ISSUE THREAD

**Issue by NielsUll** [lunet-io/scriban#74]
Given the following template:

    {{ myVal = 1.0  }}
    myVal:  {{myVal}}
    {{ if myVal > 2 }}
       Parsed as ten
    {{ else }}
       Parsed as one
    {{ end }}`

The end result will depend on the culture. If I use a culture where the decimal separator is ",", this will print "parsed as ten".

**Comment by xoofx** [comment]
Han, I thought that the parser was using proper invariant culture for terminals, but it turns out not, that's a mistake. I will fix it later today.

**Comment by xoofx** [comment]
Not sure I will have time to look at this in the coming days, a bit too busy. If you feel to do a PR (it should be just a few fixes in [Parser.Terminal.cs](https://github.com/lunet-io/scriban/blob/45435724c9a4976c58e11e913b8e4ded28ba7c05/src/Scriban/Parsing/Parser.Terminals.cs#L52)  where there are `xxx.TryParse` methods used.
