### ISSUE TITLE
DateTime Format Milliseconds missing

### ISSUE THREAD

**Issue by agmorpheus** [lunet-io/scriban#81]
I tried to format a datetime with milliseconds like this:
{{ date.format = '%d.%m.%Y - %H:%M:%S:%f'; testresult.time_stamp_send }}

It looks like that the 'f' placeholder is not supported :(

**Comment by xoofx** [comment]
The format is not a C# format, it is a [liquid/ruby format](https://apidock.com/ruby/DateTime/strftime#864-Complete-Formatting-Codes) and it is implemented here:

https://github.com/lunet-io/scriban/blob/8c125400db57bac7c3e5784b360555ab1a70e3b4/src/Scriban/Functions/DateTimeFunctions.cs#L49-L74

It seems that `%L` is the equivalent, but it's not implemented. If you have time to add the missing format (and it seems there are others),  PR welcome.
