### ISSUE TITLE
Prepend indentation to each new line when using include

### ISSUE THREAD

**Issue by j-sauer** [lunet-io/scriban#88]
Hi,

does there exist a way to prepend the indentation to each new line of the rendered template when using include?
Example:
Template a.txt:
Hello
World

Template b.txt:
        include 'a.txt'

Rendering of b.txt with indentation prepended to each new line of 'a.txt':
        Hello
        World

Thx in advance

**Comment by xoofx** [comment]
No. You can try to process the include youself maybe like `include 'a.txt' | string.replace "\n" "\n\t"` ?

**Comment by j-sauer** [comment]
Thx, this works. :)
