### ISSUE TITLE
Logical Short-Circuiting supporting?

### ISSUE THREAD

**Issue by yindongfei** [lunet-io/scriban#95]
when I use scriban, without Logical Short-Circuiting  i always need to write:
{{ if x.array.size > 0
    if x.array[0].value == 3 }}
    {{# some thing goes here }}
{{ end
    end }}

so with Logical Short-Circuiting, it could be simpler.

**Comment by yindongfei** [comment]
can i make a pr for this?

**Comment by xoofx** [comment]
Not sure to follow, do you have an example of what you would like to write?

**Comment by yindongfei** [comment]
> Not sure to follow, do you have an example of what you would like to write?

what I want to write is:

{{ if x.array.size > 0 && x.array[0].value == 3 }}
{{# without Short-Circuiting,   ^^^ will raise an exception because of array.size == 0 }}
{{# some thing goes here }}
{{ end }}

**Comment by xoofx** [comment]
As part of 1.2.8 by PR #93 , you should be able to setup `EnableRelaxedMemberAccess  = true` on template context to achieve that.

https://github.com/lunet-io/scriban/blob/686a1ed1099aeb72b51d0bca5059bfd478236c8d/src/Scriban.Tests/TestRuntime.cs#L452-L468
