### ISSUE TITLE
In Liquid syntax, 'include' that load 'for' statement raise an exception , but in scriban syntax work perfect.

### ISSUE THREAD

**Issue by moh-hassan** [lunet-io/scriban#98]
I use liquid syntax with `include` statement:

                       {% include 'products.liquid' %}

products.liquid is loaded using the  class LiquidTemplateLoader.
LiquidTemplateLoader  load the following  `products.liquid' syntax template:

			<ul id='products'>
			  {% for product1 in products %} 
				<li>
				  <h2>{{ product1.Name }}</h2>
					   Price: {{ product1.Price }}
					   ProductId: {{product1.ProductId}}				   
					   description: {{ product1.Description  }}
				</li>
			  {% endfor %}
			</ul>

When I run the following code that parse the template with include statement :

           List<Product> ProductList =  new  List<Product>
            {
            new Product {Name = "aa", Price = 12.9, Description = "zzz",ProductId = "123"},
		  new Product {Name = "bb", Price = 99.9, Description = "yyy",ProductId = "345"}
          };
			
		  var context = new TemplateContext
            {
                TemplateLoader = new LiquidTemplateLoader() ,
                MemberRenamer = member => member.Name,             
            };
              //products.liquid is loaded via LiquidTemplateLoader
		var template = Template.Parse("{% include 'products.liquid' %}",
                           lexerOptions: new LexerOptions { Mode = ScriptMode.Liquid });			
		ScriptObject scriptObject1 = new ScriptObject();      
        scriptObject1["products"] = ProductList;         
		context.PushGlobal(scriptObject1);
        var text = template.Render(context);

I get a runtime Exception:
>Object `product1` is null. Cannot access member: product1.Name

If I convert the template to scriban syntax, it works perfect.

**Comment by xoofx** [comment]
You need to parse the original document with `Template.ParseLiquid` and you also need to specify the `TemplateLoaderLexerOptions ` and `TemplateLoaderParserOptions ` on the TemplateContext (to load with templates with liquid)

```
            //products.liquid is loaded via LiquidTemplateLoader
            var template = Template.ParseLiquid("{% include 'products.liquid' %}");
            ScriptObject scriptObject1 = new ScriptObject {["products"] = ProductList};

            var context = new TemplateContext
            {
                TemplateLoader = new LiquidTemplateLoader(),
                MemberRenamer = member => member.Name,
                TemplateLoaderLexerOptions = new LexerOptions() {  Mode = ScriptMode.Liquid},
                TemplateLoaderParserOptions = new ParserOptions() {  LiquidFunctionsToScriban =  true }
            };
            context.PushGlobal(scriptObject1);
            var text = template.Render(context);
```

**Comment by xoofx** [comment]
You should also better use `LiquidTemplateContext` for better compatibility

**Comment by moh-hassan** [comment]
Thanks @xoofx  for reply.
Both your solutions including `LiquidTemplateContext`  are working fine.
Thanks for this Great Template Package.
Happy new year.
